In [1]:
from pyclassrich.gnps import Proteosafe
import matplotlib.pyplot as plt

from pyclassrich.models import class_enrichment, impact_plot, ont_graph
from pyclassrich.utils import *
import pandas as pd
import json

In [2]:
params = {
    "mzmine": False,
    "mzmine_batch": False,
    "desc": 'description',
    "gnps_taskid": 'f91f9d77ce10431d9ea08f7a5fa6b4c0',
    "gnps_nap": False,
    "nap_taskid": 'bae04809013b42c8b4e4eb7e3be3de4f',
    "classify": True,
    "normalization": {
        "perform": True,
        "type": 'TIC'
    },
    "enrich": True,
    "comparison": {
        "classes": 'Primary,Secondary',
        "field": 'ATTRIBUTE_Forest_Region',
        "test": 'ttest',
        "vthr": 0.5
    },
    "summarize": True,
    "pcoa": True,
    "pcoa_metric": 'canberra',
    "pcoa_norm": True,
    "pcoa_scale": True,
    "email": 'email@gmail.com'
}

In [3]:
params.keys()

dict_keys(['mzmine', 'mzmine_batch', 'desc', 'gnps_taskid', 'gnps_nap', 'nap_taskid', 'classify', 'normalization', 'enrich', 'comparison', 'summarize', 'pcoa', 'pcoa_metric', 'pcoa_norm', 'pcoa_scale', 'email'])

In [4]:
params

{'mzmine': False,
 'mzmine_batch': False,
 'desc': 'description',
 'gnps_taskid': 'f91f9d77ce10431d9ea08f7a5fa6b4c0',
 'gnps_nap': False,
 'nap_taskid': 'bae04809013b42c8b4e4eb7e3be3de4f',
 'classify': True,
 'normalization': {'perform': True, 'type': 'TIC'},
 'enrich': True,
 'comparison': {'classes': 'Primary,Secondary',
  'field': 'ATTRIBUTE_Forest_Region',
  'test': 'ttest',
  'vthr': 0.5},
 'summarize': True,
 'pcoa': True,
 'pcoa_metric': 'canberra',
 'pcoa_norm': True,
 'pcoa_scale': True,
 'email': 'email@gmail.com'}

In [5]:
ndict = Proteosafe(params['nap_taskid'], 'NAP')

ndict.get_nap()

ndb =  ndict.ndb
ndb = ndb.replace(' ', '')

ndb

'GNPS,SUPNAT,CHEBI'

In [6]:
type(ndict)

pyclassrich.gnps.Proteosafe

In [7]:
annotated = classify(ndict)
annotated.head()

/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

Loading database...

,cluster.index,SpectrumID,Smiles,INCHI,Identifier,Score,Ncandidates,InChI,kingdom_name,superclass_name,class_name,subclass_name,superclass_id,class_id,subclass_id,conflict,ginchikey,InchiKey
0,2,CCMSLIB00003181422,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,SN00271948,1,164,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,Organic compounds,Organic acids and derivatives,Carboxylic acids and derivatives,Dicarboxylic acids and derivatives,CHEMONTID:0000264,CHEMONTID:0000265,CHEMONTID:0000346,no,JYGXADMDTFJGBT-UHFFFAOYSA-N,JYGXADMDTFJGBT-UHFFFAOYSA-N
1,2,CCMSLIB00003181422,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,SN00312645,0.93,164,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,Organic compounds,Lipids and lipid-like molecules,Prenol lipids,Diterpenoids,CHEMONTID:0000012,CHEMONTID:0000259,CHEMONTID:0001551,no,JYGXADMDTFJGBT-UHFFFAOYSA-N,JYGXADMDTFJGBT-UHFFFAOYSA-N
2,2,CCMSLIB00003181422,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,CHEBI:95300,0.904,164,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,Organic compounds,Lipids and lipid-like molecules,Steroids and steroid derivatives,Hydroxysteroids,CHEMONTID:0000012,CHEMONTID:0000258,CHEMONTID:0001295,no,JYGXADMDTFJGBT-UHFFFAOYSA-N,JYGXADMDTFJGBT-UHFFFAOYSA-N
3,2,CCMSLIB00003181422,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,SN00263253,0.902,164,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,Organic compounds,Lipids and lipid-like molecules,Steroids and steroid derivatives,Hydroxysteroids,CHEMONTID:0000012,CHEMONTID:0000258,CHEMONTID:0001295,no,JYGXADMDTFJGBT-UHFFFAOYSA-N,JYGXADMDTFJGBT-UHFFFAOYSA-N
4,2,CCMSLIB00003181422,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,SN00378142,0.861,164,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,Organic compounds,Lipids and lipid-like molecules,Steroids and steroid derivatives,Hydroxysteroids,CHEMONTID:0000012,CHEMONTID:0000258,CHEMONTID:0001295,no,JYGXADMDTFJGBT-UHFFFAOYSA-N,JYGXADMDTFJGBT-UHFFFAOYSA-N

In [8]:
annotated.shape

(1778, 18)

In [9]:
gnps = Proteosafe(params['gnps_taskid'], 'FBMN')
gnps.get_gnps()

feat = gnps.feat
meta = gnps.meta

meta.head()

,filename,ATTRIBUTE_Sample_Number,ATTRIBUTE_Order_Injection_2965_3788,ATTRIBUTE_Plot,ATTRIBUTE_Forest_Region,ATTRIBUTE_Pertubation,ATTRIBUTE_Super_Order_APGIV_Clade,ATTRIBUTE_Order_APGIV_Order,ATTRIBUTE_Family,ATTRIBUTE_Genus,...,ATTRIBUTE_Order_APGIII,ATTRIBUTE_CS,ATTRIBUTE_AB,ATTRIBUTE_LIG,ATTRIBUTE_AFE,ATTRIBUTE_CMSF,ATTRIBUTE_Asat,ATTRIBUTE_C,ATTRIBUTE_N,ATTRIBUTE_C/N
0,167_3uL_01_06_1-33_01_3121.mzXML,167,3121,N,Secondary,Selective,Rosids,Malpighiales,Chrysobalanaceae,Licaria,...,33,St,0.015,0.115,0.013,0.275,0.051,479.418,20.287,23.631
1,168_3uL_03_07_1-65_01_3756.mzXML,168,3756,N,Secondary,Selective,Rosids,Malpighiales,Chrysobalanaceae,Licaria,...,33,St,0.015,0.115,0.013,0.275,0.051,479.418,20.287,23.631
2,169_3uL_03_07_1-91_01_3786.mzXML,169,3786,N,Secondary,Selective,Rosids,Malpighiales,Chrysobalanaceae,Licaria,...,33,St,0.015,0.115,0.013,0.275,0.051,479.418,20.287,23.631
3,196_3uL_03_07_1-54_01_3744.mzXML,196,3744,N,Secondary,Selective,Rosids,Malpighiales,Chrysobalanaceae,Licaria,...,33,St,0.015,0.115,0.013,0.275,0.051,479.418,20.287,23.631
4,239_3uL_01_06_1-25_01_3113.mzXML,239,3113,M,Primary,Preserved,Magnoliids,Laurales,Lauraceae,Licaria,...,7,St,0.005,0.151,0.010,0.401,0.083,497.319,0.029,17.262

In [10]:
feat.shape

(439, 11)

In [11]:
ctab = annotated.groupby('cluster.index').apply(lambda a: a.reset_index(drop=True).loc[0,:])
ctab.reset_index(drop=True, inplace=True)
ctab.sort_values(['cluster.index'], inplace=True)
ctabsel = ctab[['cluster.index', 'Identifier', 'InchiKey',
                'kingdom_name', 'superclass_name', 'superclass_id',
                'class_name','class_id', 'subclass_name',
                'subclass_id', 'Smiles', 'InChI']]

ctabsel.head()

,cluster.index,Identifier,InchiKey,kingdom_name,superclass_name,superclass_id,class_name,class_id,subclass_name,subclass_id,Smiles,InChI
0,2,SN00271948,JYGXADMDTFJGBT-UHFFFAOYSA-N,Organic compounds,Organic acids and derivatives,CHEMONTID:0000264,Carboxylic acids and derivatives,CHEMONTID:0000265,Dicarboxylic acids and derivatives,CHEMONTID:0000346,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...
1,4,SN00231424,JYGXADMDTFJGBT-UHFFFAOYSA-N,Organic compounds,Phenylpropanoids and polyketides,CHEMONTID:0000261,Macrolides and analogues,CHEMONTID:0000147,,,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...
2,19,SN00348475,WRXVPTMENPZUIZ-UHFFFAOYSA-N,Organic compounds,Phenylpropanoids and polyketides,CHEMONTID:0000261,Flavonoids,CHEMONTID:0000334,Flavonoid glycosides,CHEMONTID:0001111,CC1C(C(C(C(OCC2C(C(C(C(O2)Oc2c(=O)c3c(cc(cc3oc...,InChI=1S/C33H40O19/c1-10-19(37)23(41)26(44)31(...
3,23,SN00028470,NYLNHNDMNOPWAZ-ZLEFDVGRSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Fatty Acyls,CHEMONTID:0003909,Fatty acyl glycosides,CHEMONTID:0001766,,"InChI=1S/C19H32O7/c1-10-7-12(21)8-19(3,4)13(10..."
4,35,SN00034599,VDLOJRUTNRJDJO-PFCGLBSHSA-O,Organic compounds,Organic oxygen compounds,CHEMONTID:0004603,Organooxygen compounds,CHEMONTID:0000323,Alcohols and polyols,CHEMONTID:0000129,,"InChI=1S/C7H15NO5/c8-3-1-7(13,2-9)6(12)5(11)4(..."

In [12]:
ctabsel.shape

(119, 12)

In [13]:
tabgnps = ndict.tabgnps
tabgnps.head()

,cluster.index,number.of.spectra,parent.mass,precursor.charge,precursor.mass,sum.precursor.intensity.,G1,G2,G3,G4,...,RTStdErr,UniqueFileSourcesCount,LibraryID,ProteoSAFeClusterLink,AllGroups,DefaultGroups,EvenOdd,SpectrumID,Smiles,INCHI
0,2,7,363.2147,1,363.2147,4.522176e+07,0,0,0,0,...,0,7,Hydrocortisone,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,CCMSLIB00003181422,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...
1,4,7,725.4225,1,725.4225,1.102610e+07,0,0,0,0,...,0,7,Hydrocortisone,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,CCMSLIB00003455633,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...
2,19,7,741.2217,1,741.2217,1.026854e+07,0,0,0,0,...,0,7,"3-[4,5-dihydroxy-3-(3,4,5-trihydroxy-6-methylo...",https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,CCMSLIB00004718531,CC1C(C(C(C(OCC2C(C(C(C(O2)Oc2c(=O)c3c(cc(cc3oc...,InChI=1S/C33H40O19/c1-10-19(37)23(41)26(44)31(...
3,23,6,373.2208,1,373.2208,1.672149e+06,0,0,0,0,...,0,6,NaN,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,NaN,NaN,NaN
4,35,7,195.1073,1,195.1073,2.686169e+06,0,0,0,0,...,0,7,NaN,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
tabgnps.shape

(119, 23)

In [15]:
ctabsel = pd.merge(tabgnps[['cluster.index','parent.mass', 'RTMean', 'LibraryID']],
                   ctabsel, left_on='cluster.index', right_on='cluster.index')

ctabsel.head()

,cluster.index,parent.mass,RTMean,LibraryID,Identifier,InchiKey,kingdom_name,superclass_name,superclass_id,class_name,class_id,subclass_name,subclass_id,Smiles,InChI
0,2,363.2147,16.9573,Hydrocortisone,SN00271948,JYGXADMDTFJGBT-UHFFFAOYSA-N,Organic compounds,Organic acids and derivatives,CHEMONTID:0000264,Carboxylic acids and derivatives,CHEMONTID:0000265,Dicarboxylic acids and derivatives,CHEMONTID:0000346,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...
1,4,725.4225,16.9447,Hydrocortisone,SN00231424,JYGXADMDTFJGBT-UHFFFAOYSA-N,Organic compounds,Phenylpropanoids and polyketides,CHEMONTID:0000261,Macrolides and analogues,CHEMONTID:0000147,,,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...
2,19,741.2217,9.9856,"3-[4,5-dihydroxy-3-(3,4,5-trihydroxy-6-methylo...",SN00348475,WRXVPTMENPZUIZ-UHFFFAOYSA-N,Organic compounds,Phenylpropanoids and polyketides,CHEMONTID:0000261,Flavonoids,CHEMONTID:0000334,Flavonoid glycosides,CHEMONTID:0001111,CC1C(C(C(C(OCC2C(C(C(C(O2)Oc2c(=O)c3c(cc(cc3oc...,InChI=1S/C33H40O19/c1-10-19(37)23(41)26(44)31(...
3,23,373.2208,12.0004,NaN,SN00028470,NYLNHNDMNOPWAZ-ZLEFDVGRSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Fatty Acyls,CHEMONTID:0003909,Fatty acyl glycosides,CHEMONTID:0001766,,"InChI=1S/C19H32O7/c1-10-7-12(21)8-19(3,4)13(10..."
4,35,195.1073,27.3162,NaN,SN00034599,VDLOJRUTNRJDJO-PFCGLBSHSA-O,Organic compounds,Organic oxygen compounds,CHEMONTID:0004603,Organooxygen compounds,CHEMONTID:0000323,Alcohols and polyols,CHEMONTID:0000129,,"InChI=1S/C7H15NO5/c8-3-1-7(13,2-9)6(12)5(11)4(..."

In [16]:
ctabsel.shape

(119, 15)

In [17]:
feat.head()

,row ID,row m/z,row retention time,169_3uL_03_07_1-91_01_3786.mzXML Peak area,196_3uL_03_07_1-54_01_3744.mzXML Peak area,168_3uL_03_07_1-65_01_3756.mzXML Peak area,167_3uL_01_06_1-33_01_3121.mzXML Peak area,239_3uL_01_06_1-25_01_3113.mzXML Peak area,240_3uL_30_05_1-11_01_2972.mzXML Peak area,241_3uL_30_05_1-24_01_2990.mzXML Peak area,Unnamed: 10
0,2,363.214678,16.957281,7.984105e+06,7.792478e+06,7475816.375,5.307276e+06,5.852994e+06,5.005245e+06,5803849.130,NaN
1,4,725.422523,16.944662,2.405885e+06,1.022418e+05,2180724.405,1.393156e+06,1.762223e+06,1.377332e+06,1804534.155,NaN
2,6,353.265091,35.166214,1.410256e+06,2.110107e+06,1252718.320,1.132332e+06,1.199229e+06,9.326609e+05,1437400.350,NaN
3,9,381.295983,37.338333,1.276528e+06,1.858612e+06,1149778.545,1.142363e+06,1.195783e+06,9.838845e+05,1408554.330,NaN
4,19,741.221690,9.985586,1.323321e+06,4.696845e+02,3292066.106,1.465968e+03,4.122125e+06,1.079383e+06,449706.052,NaN

In [18]:
sampleid = pd.DataFrame(feat.columns[3:].tolist(),
                        columns=['sampleid'])

fnames = feat['row ID'].tolist()
feat2 = pd.concat([sampleid,
                   feat[feat.columns[3:]].T.reset_index(drop=True)],
                   axis=1)
feat2.columns = ['sampleid']+fnames
feat2 = feat2[feat2['sampleid'].str.contains('Peak area')]
feat2['sampleid'] = feat2['sampleid'].str.replace('(.+)\\.mzX?ML .+', '\\1')
mnfeat = feat2[feat2.columns[1:]][feat2[feat2.columns[1:]]!=0].min().min()
# Make it optional?
feat2.replace(0, mnfeat*(2/3), inplace=True)

feat2.head()

,sampleid,2,4,6,9,19,23,27,29,30,...,4162,4165,4166,4170,4175,4176,4241,4252,4259,4294
0,169_3uL_03_07_1-91_01_3786,7.984105e+06,2405884.900,1410255.980,1276528.075,1.323321e+06,786204.2445,351739.0390,462690.185,521851.350,...,14049.81,92.7000,67.83,130.560,59.16,76.725,316.4310,234.09,1754.080,544.0725
1,196_3uL_03_07_1-54_01_3744,7.792478e+06,102241.815,2110107.370,1858611.570,4.696845e+02,12.9200,2868.6915,247757.850,924465.355,...,2801.31,81.0900,81.09,2000.730,53.04,86.190,12.9200,95.37,4505.760,375.8700
2,168_3uL_03_07_1-65_01_3756,7.475816e+06,2180724.405,1252718.320,1149778.545,3.292066e+06,635007.5280,439601.9130,344097.945,559126.350,...,44036.99,33.6345,140.76,240.210,158.61,12.920,286.1100,584.01,292.740,341.7000
3,167_3uL_01_06_1-33_01_3121,5.307276e+06,1393155.577,1132331.985,1142362.935,1.465968e+03,15298.9175,5709.6900,217115.300,475999.130,...,12.92,446.0800,214.20,311.610,86.19,12.920,57882.8055,12.92,130.290,5640.0135
4,239_3uL_01_06_1-25_01_3113,5.852994e+06,1762223.343,1199228.755,1195783.350,4.122125e+06,235167.2670,583549.9860,119366.225,474503.040,...,2017.47,106.1100,160.14,870.102,12.92,96.390,55566.5705,12.92,135.445,392.3205

In [19]:
feat2.shape

(7, 440)

In [20]:
meta['filename'] = meta['filename'].str.replace("\\.mzXML|\\.mzML", "")
# should transformations be applied?
#feat2[feat2.columns[1:]] = feat2[feat2.columns[1:]].transform(np.log10)
meta['filename'] = meta['filename'].str.replace('\s+$', '')
feat2['sampleid'] = feat2['sampleid'].str.replace('\s+$', '')
feat2 = pd.merge(meta, feat2, left_on='filename',
                 right_on='sampleid')

feat2.head()

,filename,ATTRIBUTE_Sample_Number,ATTRIBUTE_Order_Injection_2965_3788,ATTRIBUTE_Plot,ATTRIBUTE_Forest_Region,ATTRIBUTE_Pertubation,ATTRIBUTE_Super_Order_APGIV_Clade,ATTRIBUTE_Order_APGIV_Order,ATTRIBUTE_Family,ATTRIBUTE_Genus,...,4162,4165,4166,4170,4175,4176,4241,4252,4259,4294
0,167_3uL_01_06_1-33_01_3121,167,3121,N,Secondary,Selective,Rosids,Malpighiales,Chrysobalanaceae,Licaria,...,12.92,446.0800,214.20,311.610,86.19,12.920,57882.8055,12.92,130.290,5640.0135
1,168_3uL_03_07_1-65_01_3756,168,3756,N,Secondary,Selective,Rosids,Malpighiales,Chrysobalanaceae,Licaria,...,44036.99,33.6345,140.76,240.210,158.61,12.920,286.1100,584.01,292.740,341.7000
2,169_3uL_03_07_1-91_01_3786,169,3786,N,Secondary,Selective,Rosids,Malpighiales,Chrysobalanaceae,Licaria,...,14049.81,92.7000,67.83,130.560,59.16,76.725,316.4310,234.09,1754.080,544.0725
3,196_3uL_03_07_1-54_01_3744,196,3744,N,Secondary,Selective,Rosids,Malpighiales,Chrysobalanaceae,Licaria,...,2801.31,81.0900,81.09,2000.730,53.04,86.190,12.9200,95.37,4505.760,375.8700
4,239_3uL_01_06_1-25_01_3113,239,3113,M,Primary,Preserved,Magnoliids,Laurales,Lauraceae,Licaria,...,2017.47,106.1100,160.14,870.102,12.92,96.390,55566.5705,12.92,135.445,392.3205

In [21]:
feat2.shape

(7, 462)

In [22]:
if 'filter' in params.keys():
    if params['filter']['perform']:
        fvalues = params['filter']['value'].split(',')
        meta = meta[~meta[params['filter']['field']].isin(fvalues)]

if 'keep' in params.keys():
    if params['keep']['perform']:
        fvalues = params['keep']['value'].split(',')
        meta = meta[meta[params['keep']['field']].isin(fvalues)]

if 'filter' in params.keys() or 'keep' in params.keys():
    feat2 = feat2[feat2['sampleid'].isin(meta['filename'])]

In [23]:
params['comparison']['test']=='kruskal'

False

In [24]:
from scipy import stats
from statsmodels.stats.multitest import multipletests

def multi_class(data, cn, features, method):
    if len(data.groupby(cn)) <= 2:
        raise Exception('ANOVA requires a secondary index with three or more values')
    if method=='anova':
        func = stats.f_oneway
    elif method=='kruskal':
        func = stats.kruskal
    vstats = []
    for col in fnames:
        cls = []
        for k, v in data[[cn,col]].groupby(cn):
            cls.append(v[col])
        try:
            s = func(*cls)
        except:
            s = (0,1)
        vstats.append(s)
    return pd.DataFrame(vstats)

cn = params['comparison']['field']
if params['comparison']['classes']=='all':
    cs = feat2[cn].value_counts()
    cs = cs[cs>2].index.tolist()
else:
    cs = params['comparison']['classes'].split(',')
feat3 = feat2[feat2[cn].isin(cs)]
tkruskal = multi_class(feat3, cn, fnames, 'kruskal')
pvals = tkruskal['pvalue']
pcor = multipletests(pvals, method='fdr_bh')[1]

Exception: ANOVA requires a secondary index with three or more values

In [25]:
cs

['Piaui',
 'Ceara',
 'Paraiba',
 'Pernambuco',
 'Bahia',
 'Rio Grande do Norte',
 'Minas Gerais']

In [26]:
ctabsel = pd.merge(ctabsel,
                   feat[['row ID',  'row m/z',
                         'row retention time']],
                   left_on='cluster.index',
                   right_on='row ID', how='outer')

ctabsel.head()

,cluster.index,parent.mass,RTMean,LibraryID,Identifier,InchiKey,kingdom_name,superclass_name,superclass_id,class_name,class_id,subclass_name,subclass_id,Smiles,InChI,row ID,row m/z,row retention time
0,2.0,565.1148,9.0153,"NCGC00169650-03!5,7-dihydroxy-2-(4-hydroxyphen...",SN00234934,OVMFOVNOXASTPA-UHFFFAOYSA-N,Organic compounds,Phenylpropanoids and polyketides,CHEMONTID:0000261,Flavonoids,CHEMONTID:0000334,Flavans,CHEMONTID:0000337,OCC1OC(C(O)C(O)C1O)C2=C3OC(=CC(=O)C3=C(O)C(C4O...,InChI=1S/C26H28O14/c27-6-13-18(32)21(35)23(37)...,2,565.114754,9.015315
1,5.0,595.1235,7.6607,"NCGC00385604-02!5,7-dihydroxy-2-(4-hydroxyphen...",HMDB0127287,FIAAVMJLAGNUKW-UHFFFAOYSA-N,Organic compounds,Phenylpropanoids and polyketides,CHEMONTID:0000261,Flavonoids,CHEMONTID:0000334,Flavonoid glycosides,CHEMONTID:0001111,OCC1OC(C(O)C(O)C1O)C2=C(O)C(C3OC(CO)C(O)C(O)C3...,InChI=1S/C27H30O15/c28-6-12-17(32)21(36)23(38)...,5,595.123459,7.660690
2,6.0,579.1101,3.9930,Procyanidin B2,SN00105693,XFZJEEAOWLFHDH-NFJBMHMQSA-N,Organic compounds,Organic acids and derivatives,CHEMONTID:0000264,Carboxylic acids and derivatives,CHEMONTID:0000265,Pentacarboxylic acids and derivatives,CHEMONTID:0002995,O[C@@H]([C@@H](C1=CC=C(O)C(O)=C1)O2)CC3=C2C([C...,InChI=1S/C30H26O12/c31-13-7-20(37)24-23(8-13)4...,6,579.110067,3.993017
3,11.0,725.3733,17.1468,Hydrocortisone,SN00284080,JYGXADMDTFJGBT-UHFFFAOYSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Steroids and steroid derivatives,CHEMONTID:0000258,Steroidal glycosides,CHEMONTID:0001013,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,11,725.373289,17.146844
4,15.0,607.2471,39.0418,"NCGC00180829-02_C29H44O12_Card-20(22)-enolide,...",CHEBI:3189,LPMXVESGRSUGHW-RSTGETGLSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Prenol lipids,CHEMONTID:0000259,Terpene lactones,CHEMONTID:0001283,C[C@H]1O[C@@H](O[C@H]2C[C@@H](O)[C@]3(CO)C4[C@...,InChI=1S/C29H44O12/c1-13-22(34)23(35)24(36)25(...,15,607.247058,39.041764

In [27]:
ctabsel.shape

(12624, 18)

In [28]:
ctabsel.head()

,cluster.index,parent.mass,RTMean,LibraryID,Identifier,InchiKey,kingdom_name,superclass_name,superclass_id,class_name,class_id,subclass_name,subclass_id,Smiles,InChI,row ID,row m/z,row retention time
0,2.0,565.1148,9.0153,"NCGC00169650-03!5,7-dihydroxy-2-(4-hydroxyphen...",SN00234934,OVMFOVNOXASTPA-UHFFFAOYSA-N,Organic compounds,Phenylpropanoids and polyketides,CHEMONTID:0000261,Flavonoids,CHEMONTID:0000334,Flavans,CHEMONTID:0000337,OCC1OC(C(O)C(O)C1O)C2=C3OC(=CC(=O)C3=C(O)C(C4O...,InChI=1S/C26H28O14/c27-6-13-18(32)21(35)23(37)...,2,565.114754,9.015315
1,5.0,595.1235,7.6607,"NCGC00385604-02!5,7-dihydroxy-2-(4-hydroxyphen...",HMDB0127287,FIAAVMJLAGNUKW-UHFFFAOYSA-N,Organic compounds,Phenylpropanoids and polyketides,CHEMONTID:0000261,Flavonoids,CHEMONTID:0000334,Flavonoid glycosides,CHEMONTID:0001111,OCC1OC(C(O)C(O)C1O)C2=C(O)C(C3OC(CO)C(O)C(O)C3...,InChI=1S/C27H30O15/c28-6-12-17(32)21(36)23(38)...,5,595.123459,7.660690
2,6.0,579.1101,3.9930,Procyanidin B2,SN00105693,XFZJEEAOWLFHDH-NFJBMHMQSA-N,Organic compounds,Organic acids and derivatives,CHEMONTID:0000264,Carboxylic acids and derivatives,CHEMONTID:0000265,Pentacarboxylic acids and derivatives,CHEMONTID:0002995,O[C@@H]([C@@H](C1=CC=C(O)C(O)=C1)O2)CC3=C2C([C...,InChI=1S/C30H26O12/c31-13-7-20(37)24-23(8-13)4...,6,579.110067,3.993017
3,11.0,725.3733,17.1468,Hydrocortisone,SN00284080,JYGXADMDTFJGBT-UHFFFAOYSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Steroids and steroid derivatives,CHEMONTID:0000258,Steroidal glycosides,CHEMONTID:0001013,CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O,InChI=1S/C21H30O5/c1-19-7-5-13(23)9-12(19)3-4-...,11,725.373289,17.146844
4,15.0,607.2471,39.0418,"NCGC00180829-02_C29H44O12_Card-20(22)-enolide,...",CHEBI:3189,LPMXVESGRSUGHW-RSTGETGLSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Prenol lipids,CHEMONTID:0000259,Terpene lactones,CHEMONTID:0001283,C[C@H]1O[C@@H](O[C@H]2C[C@@H](O)[C@]3(CO)C4[C@...,InChI=1S/C29H44O12/c1-13-22(34)23(35)24(36)25(...,15,607.247058,39.041764

In [29]:
fchlist = []
for fch in range(len(cs)):
    idx0 = feat2.index[np.where(feat2[cn]==cs[fch])]
    fchlist.append(feat2[fnames].apply(lambda a:
                                  np.mean(a[idx0])/np.mean(a))
                  )
fchange = pd.concat(fchlist, axis=1)
fchange.columns = [c+'_foldchange' for c in cs]

mxfchange = fchange.apply(lambda a: a[np.where(abs(np.log2(a))==np.amax(abs(np.log2(a))))[0][0]], axis=1)

ctabsel.sort_values(['row ID'], inplace=True)
ctabsel['fchange'] = mxfchange.tolist()
ctabsel['pval'] =  pvals.tolist()
ctabsel['cpval'] = pcor.tolist()

fchange.reset_index(drop=True, inplace=True)
ctabsel = pd.concat([ctabsel, fchange], axis=1)

ctabsel.head()

,cluster.index,parent.mass,RTMean,LibraryID,Identifier,InchiKey,kingdom_name,superclass_name,superclass_id,class_name,...,fchange,pval,cpval,Piaui_foldchange,Ceara_foldchange,Paraiba_foldchange,Pernambuco_foldchange,Bahia_foldchange,Rio Grande do Norte_foldchange,Minas Gerais_foldchange
0,2.0,565.1148,9.0153,"NCGC00169650-03!5,7-dihydroxy-2-(4-hydroxyphen...",SN00234934,OVMFOVNOXASTPA-UHFFFAOYSA-N,Organic compounds,Phenylpropanoids and polyketides,CHEMONTID:0000261,Flavonoids,...,0.020724,0.000216,0.001220,3.741973,0.020724,0.020724,0.020724,0.020724,0.020724,0.020724
1,5.0,595.1235,7.6607,"NCGC00385604-02!5,7-dihydroxy-2-(4-hydroxyphen...",HMDB0127287,FIAAVMJLAGNUKW-UHFFFAOYSA-N,Organic compounds,Phenylpropanoids and polyketides,CHEMONTID:0000261,Flavonoids,...,0.048135,0.019527,0.058192,3.623589,0.048135,0.048135,0.048135,0.048135,0.256296,0.048135
2,6.0,579.1101,3.9930,Procyanidin B2,SN00105693,XFZJEEAOWLFHDH-NFJBMHMQSA-N,Organic compounds,Organic acids and derivatives,CHEMONTID:0000264,Carboxylic acids and derivatives,...,0.006136,0.000073,0.000510,3.782820,0.006136,0.006136,0.006136,0.006136,0.006136,0.006136
3,11.0,725.3733,17.1468,Hydrocortisone,SN00284080,JYGXADMDTFJGBT-UHFFFAOYSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Steroids and steroid derivatives,...,0.021150,0.000024,0.000189,3.216801,0.083812,0.083812,0.083812,0.083812,0.083812,2.697761
4,15.0,607.2471,39.0418,"NCGC00180829-02_C29H44O12_Card-20(22)-enolide,...",CHEBI:3189,LPMXVESGRSUGHW-RSTGETGLSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Prenol lipids,...,0.020477,0.000216,0.001220,3.740781,0.021150,0.021150,0.021150,0.021150,0.021150,0.021150

In [30]:
ctabsel.shape

(12624, 28)

In [31]:
len(ctabsel['cluster.index'].unique())

5048

In [32]:
ctabsel[ctabsel['cluster.index'].duplicated()]

,cluster.index,parent.mass,RTMean,LibraryID,Identifier,InchiKey,kingdom_name,superclass_name,superclass_id,class_name,...,fchange,pval,cpval,Piaui_foldchange,Ceara_foldchange,Paraiba_foldchange,Pernambuco_foldchange,Bahia_foldchange,Rio Grande do Norte_foldchange,Minas Gerais_foldchange
5048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.019471,6.589070e-08,9.160840e-07,0.099738,2.866565,0.349410,2.343358,0.099738,0.099738,0.099738
5049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.880335,2.686187e-01,4.649722e-01,0.439972,1.521559,2.000439,1.353468,0.574691,0.965746,1.721963
5050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.485987,2.021576e-02,5.989292e-02,0.535181,1.373332,2.870509,0.535181,0.535181,0.535181,0.535181
5051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.005388,1.315519e-06,1.437846e-05,0.504227,0.504227,1.397876,4.586108,0.504227,0.504227,0.504227
5052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.163865,3.873627e-01,5.852862e-01,0.204879,2.734970,1.922676,0.204879,0.204879,0.204879,0.204879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.833241,2.963616e-02,7.717140e-02,0.888684,0.888684,0.888684,0.888684,2.841001,0.888684,0.888684
12620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.841001,2.963616e-02,7.717140e-02,0.900915,0.900915,0.900915,0.900915,2.638713,0.900915,0.900915
12621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.330121,2.963616e-02,7.717140e-02,0.919574,0.919574,0.919574,0.919574,2.330121,0.919574,0.919574
12622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.076693,2.963616e-02,7.717140e-02,0.934898,0.934898,0.934898,0.934898,2.076693,0.934898,0.934898
12623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.639800,2.963616e-02,7.717140e-02,0.961314,0.961314,0.961314,0.961314,1.639800,0.961314,0.961314

In [33]:
from pyclassrich.stats import *

In [25]:
df = univariate(annotated, tabgnps, 
                params, feat, meta)

df.head()

NameError: name 'univariate' is not defined

In [35]:
df.columns

Index(['cluster.index', 'parent.mass', 'RTMean', 'LibraryID', 'Identifier',
       'InchiKey', 'kingdom_name', 'superclass_name', 'superclass_id',
       'class_name', 'class_id', 'subclass_name', 'subclass_id', 'Smiles',
       'InChI', 'row ID', 'row m/z', 'row retention time', 'fchange', 'pval',
       'cpval', 'Piaui_foldchange', 'Ceara_foldchange', 'Paraiba_foldchange',
       'Pernambuco_foldchange', 'Bahia_foldchange',
       'Rio Grande do Norte_foldchange', 'Minas Gerais_foldchange'],
      dtype='object')

In [36]:
chemrich = df.copy().loc[~df['cluster.index'].isnull(),
                         ['Identifier', 'class_name', 'InChI', 
                          'pval', 'Piaui_foldchange']]

chemrich.columns = ['Compound_Name', 'Class', 'InChI', 'pvalue', 'foldchange']

clusterdf = class_enrichment(chemrich, cfield='Class', nfield='Compound_Name')
clusterdf.head()

,name,pvalues,adjustedpvalue,keycpdname,alteredMetabolites,upcount,downcount,upratio,altratio,csize,xlogp
0,Flavonoids,9.53674e-07,9.53674e-07,SN00161632,862,407,455,0.472158,0.996532,865,0.67640
1,Carboxylic acids and derivatives,9.53674e-07,9.53674e-07,SN00283311,316,143,173,0.452532,0.990596,319,2.76062
2,Steroids and steroid derivatives,9.53674e-07,9.53674e-07,SN00109197,272,132,140,0.485294,0.996337,273,4.22700
3,Prenol lipids,9.53674e-07,9.53674e-07,SN00259678,597,309,288,0.517588,0.998328,598,4.16235
4,Fatty Acyls,9.53674e-07,9.53674e-07,SN00398754,182,93,89,0.510989,1.000000,182,3.54330

In [37]:
clusterdf2 = clusterdf.sort_values('pvalues').head(10)

impact_plot(clusterdf2, chemrich, cfield='Class', nfield='Compound_Name',
            scaling_factor=5)

/home/rsilva/miniconda3/envs/pyclassrich/lib/python3.6/site-packages/pyClassRich-0.0.1-py3.6.egg/pyclassrich/models.py:386: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.

In [23]:
states = meta.loc[~meta['ATTRIBUTE_State'].isnull(), 'ATTRIBUTE_State'].unique()

if not os.path.exists('chemrich'):
    os.mkdir('chemrich')

for s in states:
    cnames = ['Identifier', 'class_name', 'InChI','pval'] + df.columns[df.columns.str.contains(s)].tolist()
    chemrich = df.loc[~df['cluster.index'].isnull(), cnames]
    chemrich.columns = ['Compound_Name', 'Class', 'InChI', 'pvalue', 'foldchange']
    clusterdf = class_enrichment(chemrich, cfield='Class', nfield='Compound_Name')
    clusterdf2 = clusterdf.sort_values('pvalues').head(10)

    impact_plot(clusterdf2, chemrich, cfield='Class', nfield='Compound_Name',
                scaling_factor=5, outdir='chemrich', filename='%s_supclass.pdf' % s)

In [24]:
s

'Rio Grande do Norte'

In [38]:
from pyclassrich.models import *

outdir = 'chemrich'

plot_classes_by_group(df, outdir)

NameError: name 'cfield' is not defined

In [40]:
get_ont_graph(ctabsel, params, cfield='Class', nfield='compound names', 
              method='kstest', outdir='chemrich', scaling_factor=10, 
              obo_file='../data/ChemOnt_2_1/ChemOnt_2_1.obo')

In [41]:
clfy = Chemont('../data/ChemOnt_2_1/ChemOnt_2_1.obo')

clfy.is_directed_acyclic_graph()

True

In [43]:
clfy.descendants('CHEMONTID:0000261')

{'CHEMONTID:0000000', 'CHEMONTID:9999999'}

In [44]:
clfy.ancestors('CHEMONTID:0000261')

{'CHEMONTID:0000029',
 'CHEMONTID:0000059',
 'CHEMONTID:0000064',
 'CHEMONTID:0000142',
 'CHEMONTID:0000145',
 'CHEMONTID:0000147',
 'CHEMONTID:0000149',
 'CHEMONTID:0000161',
 'CHEMONTID:0000181',
 'CHEMONTID:0000202',
 'CHEMONTID:0000238',
 'CHEMONTID:0000253',
 'CHEMONTID:0000334',
 'CHEMONTID:0000336',
 'CHEMONTID:0000337',
 'CHEMONTID:0000354',
 'CHEMONTID:0000356',
 'CHEMONTID:0000358',
 'CHEMONTID:0000379',
 'CHEMONTID:0000465',
 'CHEMONTID:0000476',
 'CHEMONTID:0000494',
 'CHEMONTID:0000507',
 'CHEMONTID:0001111',
 'CHEMONTID:0001136',
 'CHEMONTID:0001138',
 'CHEMONTID:0001304',
 'CHEMONTID:0001331',
 'CHEMONTID:0001361',
 'CHEMONTID:0001362',
 'CHEMONTID:0001389',
 'CHEMONTID:0001391',
 'CHEMONTID:0001532',
 'CHEMONTID:0001533',
 'CHEMONTID:0001536',
 'CHEMONTID:0001583',
 'CHEMONTID:0001584',
 'CHEMONTID:0001586',
 'CHEMONTID:0001587',
 'CHEMONTID:0001594',
 'CHEMONTID:0001607',
 'CHEMONTID:0001608',
 'CHEMONTID:0001612',
 'CHEMONTID:0001614',
 'CHEMONTID:0001615',
 'CHEMONTID:0001630',
 'CHEMONTID:0001631',
 'CHEMONTID:0001632',
 'CHEMONTID:0001633',
 'CHEMONTID:0001645',
 'CHEMONTID:0001649',
 'CHEMONTID:0001710',
 'CHEMONTID:0001711',
 'CHEMONTID:0001712',
 'CHEMONTID:0001737',
 'CHEMONTID:0001738',
 'CHEMONTID:0001739',
 'CHEMONTID:0001741',
 'CHEMONTID:0001742',
 'CHEMONTID:0001743',
 'CHEMONTID:0001758',
 'CHEMONTID:0001759',
 'CHEMONTID:0001761',
 'CHEMONTID:0001787',
 'CHEMONTID:0001788',
 'CHEMONTID:0001800',
 'CHEMONTID:0001802',
 'CHEMONTID:0001803',
 'CHEMONTID:0001808',
 'CHEMONTID:0001817',
 'CHEMONTID:0001827',
 'CHEMONTID:0001828',
 'CHEMONTID:0001890',
 'CHEMONTID:0001900',
 'CHEMONTID:0002106',
 'CHEMONTID:0002355',
 'CHEMONTID:0002503',
 'CHEMONTID:0002504',
 'CHEMONTID:0002505',
 'CHEMONTID:0002506',
 'CHEMONTID:0002507',
 'CHEMONTID:0002508',
 'CHEMONTID:0002523',
 'CHEMONTID:0002551',
 'CHEMONTID:0002568',
 'CHEMONTID:0002569',
 'CHEMONTID:0002580',
 'CHEMONTID:0002581',
 'CHEMONTID:0002582',
 'CHEMONTID:0002583',
 'CHEMONTID:0002585',
 'CHEMONTID:0002586',
 'CHEMONTID:0002587',
 'CHEMONTID:0002588',
 'CHEMONTID:0002589',
 'CHEMONTID:0002590',
 'CHEMONTID:0002591',
 'CHEMONTID:0002592',
 'CHEMONTID:0002593',
 'CHEMONTID:0002594',
 'CHEMONTID:0002595',
 'CHEMONTID:0002596',
 'CHEMONTID:0002597',
 'CHEMONTID:0002598',
 'CHEMONTID:0002599',
 'CHEMONTID:0002600',
 'CHEMONTID:0002601',
 'CHEMONTID:0002602',
 'CHEMONTID:0002603',
 'CHEMONTID:0002604',
 'CHEMONTID:0002605',
 'CHEMONTID:0002606',
 'CHEMONTID:0002612',
 'CHEMONTID:0002614',
 'CHEMONTID:0002615',
 'CHEMONTID:0002616',
 'CHEMONTID:0002617',
 'CHEMONTID:0002642',
 'CHEMONTID:0002643',
 'CHEMONTID:0002644',
 'CHEMONTID:0002650',
 'CHEMONTID:0002651',
 'CHEMONTID:0002652',
 'CHEMONTID:0002682',
 'CHEMONTID:0002683',
 'CHEMONTID:0002684',
 'CHEMONTID:0002685',
 'CHEMONTID:0002686',
 'CHEMONTID:0002687',
 'CHEMONTID:0002689',
 'CHEMONTID:0002690',
 'CHEMONTID:0002708',
 'CHEMONTID:0002709',
 'CHEMONTID:0002710',
 'CHEMONTID:0002711',
 'CHEMONTID:0002712',
 'CHEMONTID:0002713',
 'CHEMONTID:0002714',
 'CHEMONTID:0002715',
 'CHEMONTID:0002716',
 'CHEMONTID:0002754',
 'CHEMONTID:0002810',
 'CHEMONTID:0002819',
 'CHEMONTID:0002820',
 'CHEMONTID:0002821',
 'CHEMONTID:0002830',
 'CHEMONTID:0002831',
 'CHEMONTID:0002832',
 'CHEMONTID:0002833',
 'CHEMONTID:0002896',
 'CHEMONTID:0002897',
 'CHEMONTID:0002898',
 'CHEMONTID:0002900',
 'CHEMONTID:0002901',
 'CHEMONTID:0002902',
 'CHEMONTID:0002907',
 'CHEMONTID:0002908',
 'CHEMONTID:0002909',
 'CHEMONTID:0002914',
 'CHEMONTID:0002915',
 'CHEMONTID:0002934',
 'CHEMONTID:0002935',
 'CHEMONTID:0002988',
 'CHEMONTID:0002989',
 'CHEMONTID:0002990',
 'CHEMONTID:0002991',
 'CHEMONTID:0002992',
 'CHEMONTID:0002993',
 'CHEMONTID:0002994',
 'CHEMONTID:0002996',
 'CHEMONTID:0002997',
 'CHEMONTID:0003002',
 'CHEMONTID:0003003',
 'CHEMONTID:0003004',
 'CHEMONTID:0003005',
 'CHEMONTID:0003006',
 'CHEMONTID:0003012',
 'CHEMONTID:0003013',
 'CHEMONTID:0003190',
 'CHEMONTID:0003191',
 'CHEMONTID:0003405',
 'CHEMONTID:0003406',
 'CHEMONTID:0003407',
 'CHEMONTID:0003415',
 'CHEMONTID:0003465',
 'CHEMONTID:0003466',
 'CHEMONTID:0003467',
 'CHEMONTID:0003470',
 'CHEMONTID:0003471',
 'CHEMONTID:0003472',
 'CHEMONTID:0003473',
 'CHEMONTID:0003474',
 'CHEMONTID:0003475',
 'CHEMONTID:0003478',
 'CHEMONTID:0003479',
 'CHEMONTID:0003480',
 'CHEMONTID:0003484',
 'CHEMONTID:0003485',
 'CHEMONTID:0003486',
 'CHEMONTID:0003496',
 'CHEMONTID:0003501',
 'CHEMONTID:0003502',
 'CHEMONTID:0003503',
 'CHEMONTID:0003504',
 'CHEMONTID:0003505',
 'CHEMONTID:0003506',
 'CHEMONTID:0003507',
 'CHEMONTID:0003508',
 'CHEMONTID:0003509',
 'CHEMONTID:0003510',
 'CHEMONTID:0003511',
 'CHEMONTID:0003512',
 'CHEMONTID:0003513',
 'CHEMONTID:0003514',
 'CHEMONTID:0003515',
 'CHEMONTID:0003516',
 'CHEMONTID:0003520',
 'CHEMONTID:0003523',
 'CHEMONTID:0003524',
 'CHEMONTID:0003525',
 'CHEMONTID:0003526',
 'CHEMONTID:0003527',
 'CHEMONTID:0003528',
 'CHEMONTID:0003530',
 'CHEMONTID:0003531',
 'CHEMONTID:0003532',
 'CHEMONTID:0003533',
 'CHEMONTID:0003534',
 'CHEMONTID:0003535',
 'CHEMONTID:0003540',
 'CHEMONTID:0003541',
 'CHEMONTID:0003542',
 'CHEMONTID:0003551',
 'CHEMONTID:0003552',
 'CHEMONTID:0003553',
 'CHEMONTID:0003554',
 'CHEMONTID:0003555',
 'CHEMONTID:0003556',
 'CHEMONTID:0003579',
 'CHEMONTID:0003580',
 'CHEMONTID:0003587',
 'CHEMONTID:0003588',
 'CHEMONTID:0003637',
 'CHEMONTID:0003638',
 'CHEMONTID:0003639',
 'CHEMONTID:0003640',
 'CHEMONTID:0003641',
 'CHEMONTID:0003642',
 'CHEMONTID:0003643',
 'CHEMONTID:0003644',
 'CHEMONTID:0003645',
 'CHEMONTID:0003646',
 'CHEMONTID:0003647',
 'CHEMONTID:0003648',
 'CHEMONTID:0003649',
 'CHEMONTID:0003650',
 'CHEMONTID:0003651',
 'CHEMONTID:0003652',
 'CHEMONTID:0003678',
 'CHEMONTID:0003679',
 'CHEMONTID:0003680',
 'CHEMONTID:0003681',
 'CHEMONTID:0004154',
 'CHEMONTID:0004181',
 'CHEMONTID:0004182',
 'CHEMONTID:0004510',
 'CHEMONTID:0004559',
 'CHEMONTID:0004561',
 'CHEMONTID:0004785',
 'CHEMONTID:0004818',
 'CHEMONTID:0004821',
 'CHEMONTID:0004828',
 'CHEMONTID:0004829'}

In [45]:
clfy.edges_to_parents('CHEMONTID:0000261')

• Phenylpropanoids and polyketides ⟶ is_a ⟶ Organic compounds

In [46]:
clfy.edges_to_children('CHEMONTID:0000261')

• Phenylpropanoids and polyketides ⟵ is_a ⟵ Cinnamaldehydes
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Macrolactams
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Coumarins and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Macrolides and analogues
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Tetracyclines
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Tannins
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Stilbenes
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Flavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Cinnamic acids and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Brevetoxins and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Neoflavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Aurone flavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Depsides and depsidones
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Isochromanequinones
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Kavalactones
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Ochratoxins and related substances
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Saxitoxins, gonyautoxins, and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Okadaic acids and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Ciguatera toxins
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Sterigmatocystins
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Isocoumarins and derivatives
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Macrolide lactams
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Anthracyclines
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Isoflavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Homoisoflavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Phenylpropanoic acids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Alpha-methyldeoxybenzoin flavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ 3,4-dihydrocoumarins
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Diarylheptanoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Cinnamyl alcohols
• Phenylpropanoids and polyketides ⟵ is_a ⟵ 1,2-diaryl-2-propen-1-ols
• Phenylpropanoids and polyketides ⟵ is_a ⟵ 2-arylbenzofuran flavonoids
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Angucyclines
• Phenylpropanoids and polyketides ⟵ is_a ⟵ Linear 1,3-diarylpropanoids

In [53]:
ndb

'GNPS,HMDB,SUPNAT,CHEBI,DRUGBANK,FooDB'

In [54]:
db = get_db(ndb)
db.head()

Loading database...

,id,MonoisotopicMass,InChI,SMILES,Identifier,InChIKey2,InChIKey1,MolecularFormula,kingdom_name,kingdom_id,superclass_name,superclass_id,class_name,class_id,subclass_name,subclass_id,ref
0,42516,2178.986,InChI=1S/C98H138N24O33/c1-5-52(4)82(96(153)122...,CCC(C)C(C(=O)N1CCCC1C(=O)NC(CCC(=O)O)C(=O)NC(C...,DB00006,GEJPAHFPSA,OIRCOABEOLEUMC,C98H138N24O33,Organic compounds,CHEMONTID:0000000,,,Polypeptides,CHEMONTID:0003298,,,drugdb
1,42517,1268.641,InChI=1S/C59H84N18O14/c1-31(2)22-40(49(82)68-3...,CC(C)CC(C(=O)NC(CCCN=C(N)N)C(=O)N1CCCC1C(=O)NN...,DB00014,URPVMXJPSA,BLCLNMBMMGCOAS,C59H84N18O14,Organic compounds,CHEMONTID:0000000,,,Carboxylic acids and derivatives,CHEMONTID:0000265,,,drugdb
2,42518,1810.033,InChI=1S/C96H135N19O16/c1-50(2)36-71(105-79(11...,CC(C)CC(C(=O)NC(C)C(=O)NC(C(C)C)C(=O)NC(C(C)C)...,DB00027,MWWSRJDJSA,NDAYQJDHGXTBJL,C96H135N19O16,Organic compounds,CHEMONTID:0000000,,,Polypeptides,CHEMONTID:0003298,,,drugdb
3,42519,1068.427,InChI=1S/C46H64N14O12S2/c47-35(62)15-14-29-40(...,C1CC(N(C1)C(=O)C2CSSCCC(=O)NC(C(=O)NC(C(=O)NC(...,DB00035,NXBWRCJVSA,NFLWUMRGJYTJIN,C46H64N14O12S2,Organic compounds,CHEMONTID:0000000,,,Carboxylic acids and derivatives,CHEMONTID:0000265,,,drugdb
4,42520,1429.670,InChI=1S/C70H92ClN17O14/c1-39(2)31-52(61(94)82...,CC(C)CC(C(=O)NC(CCCN=C(N)N)C(=O)N1CCCC1C(=O)NC...,DB00050,MHWMIDJBSA,SBNPWPIBESPSIF,C70H92ClN17O14,Organic compounds,CHEMONTID:0000000,,,Polypeptides,CHEMONTID:0003298,,,drugdb

In [55]:
mol_set = db2set(db, obo_file='../data/ChemOnt_2_1/ChemOnt_2_1.obo')

In [56]:
mol_set.keys()

dict_keys(['superclass_name', 'class_name', 'subclass_name'])

In [57]:
mol_set['superclass_name']

{'CHEMONTID:0000002': ['JEYYJJQJMHKACT-UHFFFAOYSA-N',
  'NEONEXNCIMCJRM-UHFFFAOYSA-N',
  'DVWGSXKIJGQKEF-UHFFFAOYSA-N',
  'KQYZOOUJAWUDAP-WCBMZHEXSA-N',
  'BZQIGYZFDBINJR-JTQLQIEISA-N',
  'XIXYQIQKYPKGKP-UHFFFAOYSA-N',
  'HWIIAAVGRHKSOJ-UHFFFAOYSA-N',
  'XSDWOOUKAMFWTM-UHFFFAOYSA-N',
  'DWEJXROSWIHNMK-UHFFFAOYSA-N',
  'LFHFCVPACJWBCR-WUKNDPDISA-N',
  'UNCWSEUXPWPQOC-IUCAKERBSA-N',
  'UNCWSEUXPWPQOC-DTWKUNHWSA-N',
  'UNCWSEUXPWPQOC-RKDXNWHRSA-N',
  'UNCWSEUXPWPQOC-BDAKNGLRSA-N',
  'WBYNLYPFJGNKTK-UHFFFAOYSA-N',
  'FCWHQYPAILTVPV-UHFFFAOYSA-N',
  'KTGYDKACJATEDM-UHFFFAOYSA-N',
  'RYFOJXFXERAMLS-UHFFFAOYSA-N',
  'AZHUOPNKXMFIAA-UHFFFAOYSA-N',
  'SRZFMMDHZCOFRB-UHFFFAOYSA-O',
  'SZUXCWXZQUMIPM-UHFFFAOYSA-O',
  'TVZPXEZTWRAIID-UHFFFAOYSA-N',
  'UNSLQFMTPYHZDA-UHFFFAOYSA-N',
  'COCFIBRMFPWUDW-UHFFFAOYSA-O',
  'PJEJONPCMMXOCT-QMMMGPOBSA-N',
  'PJEJONPCMMXOCT-MRVPVSSYSA-N',
  'ZVHUQIMPAVOVTR-UHFFFAOYSA-N',
  'VBNSXUOMQDHOKL-VIFPVBQESA-M',
  'VBNSXUOMQDHOKL-SECBINFHSA-M',
  'KNBIEZUXUHXIQJ-UHFFFAOYSA-M',
  'YLBYAZHPXJQIPP-UHFFFAOYSA-N',
  'LJONQULKOKMKBR-LURJTMIESA-N',
  'LJONQULKOKMKBR-ZCFIWIBFSA-N',
  'BVAPMGBAMQRYKG-SNAWJCMRSA-N',
  'OFQDWONQQAAIFF-UHFFFAOYSA-N',
  'YGGIJLHBKXDFJG-UHFFFAOYSA-M',
  'GLLIXWMNULCIKR-MRVPVSSYSA-N',
  'CAINGBSRNIKXHV-INIZCTEOSA-N',
  'CAINGBSRNIKXHV-MRXNPFEDSA-N',
  'KHYIWRGNPLBXDS-UHFFFAOYSA-N',
  'UBSOPKLAYPNFFN-UHFFFAOYSA-N',
  'LKKQHIJMWGQCSO-UHFFFAOYSA-N',
  'QQTFUUWRTCNLLD-UHFFFAOYSA-O',
  'CLDVQGQXZUANQB-UHFFFAOYSA-O',
  'HXUSBYHCSYTKGG-UHFFFAOYSA-O',
  'IMNUDUZCMFTLBK-UHFFFAOYSA-N',
  'ACEWBOIMCFVVKN-VIFPVBQESA-N',
  'ACEWBOIMCFVVKN-SECBINFHSA-N',
  'OTZYLKUZVWKKHG-UHFFFAOYSA-O',
  'ARLHWYFAPHJCJT-UHFFFAOYSA-N',
  'YZCJVJZTKWUFKI-UHFFFAOYSA-N',
  'KSJDWXPZNDRADG-UHFFFAOYSA-N',
  'QGNYADYMHMVJOG-UHFFFAOYSA-N',
  'AQLCOILGCBDQDZ-UHFFFAOYSA-N',
  'AFMKFKKHDZRFAA-UHFFFAOYSA-N',
  'NLHYHLPSUOFMHW-UHFFFAOYSA-N',
  'XZJXQDVYKGQZLY-UHFFFAOYSA-N',
  'ZONQVNWUCWMRBX-UHFFFAOYSA-N',
  'YFBZUWUJSCLVST-UHFFFAOYSA-N',
  'KCADUUDDTBWILK-UHFFFAOYSA-N',
  'ZMQAAUBTXCXRIC-UHFFFAOYSA-N',
  'VHVOLFRBFDOUSH-IHWYPQMZSA-N',
  'JNXGHQDZQVYCKB-UHFFFAOYSA-N',
  'HNZVBTGMMGOJBN-SNVBAGLBSA-N',
  'MOTPGUUWWLWTDO-UHFFFAOYSA-N',
  'RJHXEPLSJAVTFW-UHFFFAOYSA-N',
  'QQCVJPOOVIUDTI-UHFFFAOYSA-N',
  'IKUBQGOYKPKCKQ-UHFFFAOYSA-N',
  'VTSAALCORKKACE-ZETCQYMHSA-N',
  'OHDFENKFSKIFBJ-UHFFFAOYSA-N',
  'HBAUAIPLAXNUIM-UHFFFAOYSA-M',
  'LALSYIKKTXUSLG-UHFFFAOYSA-M',
  'UGAGZMGJJFSKQM-QMMMGPOBSA-M',
  'UGAGZMGJJFSKQM-MRVPVSSYSA-M',
  'YXDPSLZCSQBRGS-UHFFFAOYSA-N',
  'LQIYOSKKKUPTRP-UHFFFAOYSA-N',
  'DISYDHABSCTQFK-UHFFFAOYSA-N',
  'JQZASRHQYJJUCE-OWOJBTEDSA-N',
  'DNNSYXUCMMUSNY-UHFFFAOYSA-N',
  'MAJHXCZOBHSOSD-UHFFFAOYSA-N',
  'MHENVRWNXCCIFX-QMMMGPOBSA-N',
  'AIHVXKPMAWGFLZ-VIFPVBQESA-N',
  'AIHVXKPMAWGFLZ-SECBINFHSA-N',
  'VPMRYZZHLGCIIT-VIFPVBQESA-N',
  'VPMRYZZHLGCIIT-SECBINFHSA-N',
  'FCSPXCQJNMMNMO-UHFFFAOYSA-N',
  'LSVKXYMPPYKGAB-UHFFFAOYSA-N',
  'XZTWUMWIHHLFDI-SNVBAGLBSA-N',
  'CNOJMNDAJUZLGJ-ZCFIWIBFSA-N',
  'QAUOMEZVECUWFA-LURJTMIESA-N',
  'QAUOMEZVECUWFA-ZCFIWIBFSA-N',
  'HWCCVMGTQFWJSS-ZCFIWIBFSA-N',
  'KWILGNNWGSNMPA-LURJTMIESA-N',
  'KWILGNNWGSNMPA-ZCFIWIBFSA-N',
  'WHEIRCBYUYIIMR-LURJTMIESA-N',
  'WHEIRCBYUYIIMR-ZCFIWIBFSA-N',
  'PDOTWWQNXPRSKT-FNORWQNLSA-N',
  'SDGOMJUKDHSPPU-JTQLQIEISA-N',
  'ORFFGRQMMWVHIB-UHFFFAOYSA-N',
  'ZMLVTKKIMDNHCP-UHFFFAOYSA-N',
  'UKFAWRZYFYOXEG-UHFFFAOYSA-N',
  'UMHYKDRIZFCRLF-UHFFFAOYSA-N',
  'CZNAGSOSJIGERX-JTQLQIEISA-N',
  'CZNAGSOSJIGERX-SNVBAGLBSA-N',
  'MZNDBUPBPVNTQD-UHFFFAOYSA-N',
  'FDAOUJHEWGCELW-QMMMGPOBSA-N',
  'WDZMAKLDQJGEFI-SECBINFHSA-N',
  'JGHXNKLHSHDHDG-UHFFFAOYSA-N',
  'LNEPPGKBSBTFDF-GOZDTHDVSA-N',
  'MMRYEEUZQALQGT-UHFFFAOYSA-N',
  'SLLMHZXMVHNZOR-UHFFFAOYSA-N',
  'AIJQFRIMFUSUEZ-RXMQYKEDSA-N',
  'OEVSVHJSZJTZDW-CDUCUWFYSA-N',
  'DBVDPKVOHHNTRU-YFKPBYRVSA-N',
  'DCRGULRFFRBGTR-SNVBAGLBSA-N',
  'ZNVGYHOBTCWGTO-SNVBAGLBSA-N',
  'NNADFONXCWKMRA-YFKPBYRVSA-N',
  'NNADFONXCWKMRA-RXMQYKEDSA-N',
  'JELREGOQGBYVKW-UHFFFAOYSA-N',
  'RDTZWOOKIBKFCJ-UHFFFAOYSA-M',
  'UNBPACVPFRFNDG-UHFFFAOYSA-N',
  'NUAKROUEBAHTAU-UHFFFAOYSA-N',
  'STSOHAOGZMLWFR-CDUCUWFYSA-N',
  'STSOHAOGZMLWFR-MLUIRONXSA-N',
  'STSOHAOGZMLWFR-ANLVUFKYSA-N',
  'CYXPOLJZVSSCOT-ZCFIWIBFSA-N',
  'IBNFFIKIHHCABM-WEWAHIQMSA-N',
  'MCGFFMYLLRUZGJ-VIFPVBQESA-N',
  'MCGFFMYLLRUZGJ-SECBINFHSA-N',
  'PQKZXVQPXILLIC-VIFPVBQESA-N',
  'PQKZXVQPXILLIC-SECBINFHSA-N',
  'XRDVWVFUUCJPOL-UHFFFAOYSA-N',
  'HRQTURYIXBOKDA-JXKNXFGGSA-N',
  'LAVJUISMIZTLGI-YFKPBYRVSA-N',
  'MEQAIIPMRAUIPD-SNVBAGLBSA-N',
  'AWJLARVNMUSPPN-VHWMUFPASA-N',
  'RKIATQDHYLUPSL-ONEGZZNKSA-N',
  'STASDEBCLZPNAY-LURJTMIESA-N',
  'BICFOGDDVXBEJA-UHFFFAOYSA-N',
  'YLCDRVHCVJDESI-UHFFFAOYSA-N',
  'KSJQONHZJMPCKV-UHFFFAOYSA-N',
  'UUSIZFXIVNATEL-UHFFFAOYSA-N',
  'FMKMKBLHMONXJM-UHFFFAOYSA-N',
  'GKBOAQBGBCSHPA-UHFFFAOYSA-N',
  'WVYWIVZMXIVOBQ-UHFFFAOYSA-M',
  'COPXXGSWRBNVHM-BYPYZUCNSA-M',
  'COPXXGSWRBNVHM-SCSAIBSYSA-M',
  'ZYSGUISDGDUDLK-UHFFFAOYSA-N',
  'MFDAXYLPBXZFOM-UHFFFAOYSA-N',
  'OCKIKBXJWZGGOE-UHFFFAOYSA-N',
  'LKVCVFMHMHYDOF-UHFFFAOYSA-N',
  'YFACVTYKPNEKQK-UHFFFAOYSA-O',
  'FEDUCLWLNMVLQI-UHFFFAOYSA-M',
  'ZMZMETFCSBGHFT-UHFFFAOYSA-M',
  'CSECZRPVODEEQZ-UHFFFAOYSA-O',
  'WYFNKSHKGSUPOR-UHFFFAOYSA-N',
  'HDDCFDZWKIPWDA-VIFPVBQESA-N',
  'HDDCFDZWKIPWDA-SECBINFHSA-N',
  'FDXUZISVYDSGPM-UHFFFAOYSA-N',
  'ONQKSKDLYYDFLL-UHFFFAOYSA-N',
  'JFUOUIPRAAGUGF-NKWVEPMBSA-N',
  'PWICZRDDLGZHDM-UHFFFAOYSA-N',
  'WGCDETRNVPBSFG-UHFFFAOYSA-N',
  'MJJMGWDMMYKRMM-UHFFFAOYSA-N',
  'GTZVMEHLIMDKTK-UHFFFAOYSA-N',
  'PUVRCZAAJCWOBV-SECBINFHSA-N',
  'IVFIWGSRKYSLLR-UHFFFAOYSA-N',
  'BWKMGYQJPOAASG-VIFPVBQESA-N',
  'BWKMGYQJPOAASG-SECBINFHSA-N',
  'JHLDJOBIUVJSTG-UHFFFAOYSA-O',
  'RLNQBGQGMYNOCX-ZCFIWIBFSA-N',
  'BYNKVNIMSRBGPJ-XPUUQOCRSA-N',
  'PPIBJOQGAJBQDF-CBAPKCEASA-N',
  'PPIBJOQGAJBQDF-IONNQARKSA-N',
  'PPIBJOQGAJBQDF-VXNVDRBHSA-N',
  'PPIBJOQGAJBQDF-APPZFPTMSA-N',
  'BWGYBDMWPGTABF-UHFFFAOYSA-N',
  'OTCVOVCBERGAOC-JTQLQIEISA-N',
  'ANFMKCSQXDEJMT-UHFFFAOYSA-N',
  'XFEDBAPBLDLPFC-VIFPVBQESA-N',
  'GELIQHGXKLXDKQ-QMMMGPOBSA-N',
  'GELIQHGXKLXDKQ-MRVPVSSYSA-N',
  'XMBFPFCDVMKUIN-JTQLQIEISA-M',
  'XMBFPFCDVMKUIN-SNVBAGLBSA-N',
  'JPAUXIBZDXSDTN-ONEGZZNKSA-N',
  'ICZVDXDXJQCDOJ-UHFFFAOYSA-N',
  'MBYZKNWOAOHALV-HZGVNTEJSA-N',
  'GLNRAZLQBMAROT-LURJTMIESA-N',
  'UIPNPFUNPXYKGP-ZETCQYMHSA-N',
  'NFWHHUCJMAPGHE-ZETCQYMHSA-M',
  'NFWHHUCJMAPGHE-SSDOTTSWSA-M',
  'MWNPFZGFCGCPRJ-VISXPRAWSA-N',
  'VBXNJRCPOOQJML-SNVBAGLBSA-N',
  'DNEAIJBQFZFHAA-UHFFFAOYSA-N',
  'KQSFHAWSULOGRI-IQPPKSMTSA-N',
  'GPMLOKDWIQLIST-FARCUNLSSA-N',
  'OPRAONAUWNNOOV-ZETCQYMHSA-N',
  'RGFJEBQREIGRFX-YUMQZZPRSA-N',
  'CXMIZBYDTIGEEV-ZETCQYMHSA-N',
  'AWMAVDJHARVPNN-ZETCQYMHSA-N',
  'PBIVMDBQFLBXGD-FJXKBIBVSA-N',
  'WEYGYSPOSHISSP-UHFFFAOYSA-N',
  'USYQORVUJKRYHT-LDWIPMOCSA-N',
  'NOFZMDGMQKRLIV-UHFFFAOYSA-N',
  'UKJCZGTZCWPKLF-UHFFFAOYSA-N',
  'XOKCJXZZNAUIQN-IUCAKERBSA-N',
  'XGCCBKJIKOMKRR-WCBMZHEXSA-N',
  'AFTDVOKQJZAVLI-BQBZGAKWSA-N',
  'JSJALGZAHYXCKU-LURJTMIESA-N',
  'QITGEYGQQODBRX-UHFFFAOYSA-N',
  'VOBCVFFLVMMPPK-UHFFFAOYSA-N',
  'FDQGNLOWMMVRQL-UHFFFAOYSA-N',
  'GPVQJVMIYJKIFC-OCAPTIKFSA-N',
  'NRRUIDNYDPVJEP-YUMQZZPRSA-N',
  'VKWAZWHXIDFFQT-QMMMGPOBSA-N',
  'CLAHRMVMJHLHQE-VURMDHGXSA-N',
  'BXJMRXBQNLKDCI-UHFFFAOYSA-N',
  'UIKROCXWUNQSPJ-SECBINFHSA-N',
  'SZDFIVJGWVHZAV-QMMMGPOBSA-O',
  'SZDFIVJGWVHZAV-MRVPVSSYSA-O',
  'RSNDUSNTDLGWQM-UHFFFAOYSA-N',
  'GQLSEYOOXBRDFZ-JTQLQIEISA-N',
  'CPWSAKUPXWXJPQ-ZCFIWIBFSA-N',
  'NUJFYQDHTBBYKQ-ZETCQYMHSA-N',
  'YDWIHMVUUGVOLZ-UHFFFAOYSA-N',
  'OAHZGBQVTKRBNI-UHFFFAOYSA-N',
  'ZYUPLDFSBVJNIH-UHFFFAOYSA-M',
  'ASJWEHCPLGMOJE-ZCZDTUGYSA-N',
  'VTZWDWJFPLLWGN-UHFFFAOYSA-N',
  'ZZXGPXHOIOCZQR-ZETCQYMHSA-O',
  'CMRSAXKMZYZULD-MRVPVSSYSA-N',
  'GVUAFSNSBZBVES-GQCTYLIASA-N',
  'VSHHGEHQSPTVTP-PLNGDYQASA-N',
  'VSHHGEHQSPTVTP-SNAWJCMRSA-N',
  'FEEGMVBAILJAQO-DAXSKMNVSA-N',
  'FEEGMVBAILJAQO-QPJJXVBHSA-N',
  'PTVNMTAUAGZCGN-YUMQZZPRSA-N',
  'JRMIDKPHJPTJMM-LURJTMIESA-N',
  'HOEVDNBLHKNVMQ-MRVPVSSYSA-N',
  'DKYYYKAZIVROLW-ZETCQYMHSA-N',
  'DKYYYKAZIVROLW-SSDOTTSWSA-N',
  'VOONDAZISKQGNR-YCRREMRBSA-N',
  'YVCGUHJUVIFAOU-UHFFFAOYSA-N',
  'MUSYKEZISZZBFO-UHFFFAOYSA-M',
  'DNXWUWRYEBKICC-GQCTYLIASA-N',
  'JMJXBWVQZRFIHZ-XCBNKYQSSA-N',
  'YGPGUEZTBZXORL-PVOUKABXSA-N',
  'UOMUHNNOLZVNSH-YUMQZZPRSA-N',
  'PXFYAFDHWSXVLU-MRVPVSSYSA-N',
  'LJCIESHRVPWJJM-UHFFFAOYSA-N',
  'YTNGLQLQPPYEAT-PSASIEDQSA-N',
  'HOXZLCMLRLXRIN-QPJJXVBHSA-N',
  'UJYUDTPLHOZSGT-OCAPTIKFSA-N',
  'BFAPKXQOLRZYTB-LHLIQPBNSA-N',
  'XNGDDFPFJFPWRU-ZETCQYMHSA-N',
  'YMQOWBARIGEIMW-GMSGAONNSA-N',
  'DNRLWLBGSCPICC-BBBLOLIVSA-N',
  'BXFIHDMPMGLIDF-POYBYMJQSA-N',
  'BXFIHDMPMGLIDF-HTRCEHHLSA-N',
  'ZQHMVQITCFVJFA-SNVBAGLBSA-N',
  'VAFOLTKCMXTVQD-FNORWQNLSA-N',
  'WKABNSOLXPEPJQ-VBKOABKLSA-N',
  'WTXFBCVFHRHFQD-HDMKULJXSA-N',
  'PQEKEYKFSWTAJS-UHFFFAOYSA-N',
  'WMGURONUQLCIRS-QLGZBTQXSA-N',
  'UNANDJIJRBQOOF-UHFFFAOYSA-N',
  'CKDSCAKQBRZWHH-UHFFFAOYSA-N',
  'FYDVPEVHFUBOJG-QMMMGPOBSA-N',
  'FYDVPEVHFUBOJG-MRVPVSSYSA-N',
  'NOJVXIYSKYICFF-PSASIEDQSA-N',
  'DFWGSIJBMOBCST-ONEGZZNKSA-N',
  'SXCIHQFSGVEIHK-HUGTUPKYSA-N',
  'FIUFNZNVZDLYHQ-QBBOHKLWSA-N',
  'BABJXHCBFYMVBG-RNJXMRFFSA-N',
  'BABJXHCBFYMVBG-XLPZGREQSA-N',
  'HKKIPBZGPPCEMB-YFKPBYRVSA-N',
  'YIRAEUKOPKEBHB-WKEGUHRASA-N',
  'APBQCQCZDOLYQU-HZGVNTEJSA-N',
  'APBQCQCZDOLYQU-MUWHJKNJSA-N',
  'YMKWNRDVGOVSHY-MAUMQABQSA-N',
  'YMKWNRDVGOVSHY-RBXMUDONSA-N',
  'RJXJHEYXZURDJH-UHFFFAOYSA-N',
  'OXOYFOKGDOZNLQ-JTQLQIEISA-N',
  'XPXHSUOIQNJEQI-GJMOJQLCSA-N',
  'XPXHSUOIQNJEQI-CSMHCCOUSA-N',
  'HAMNKHJHOZJTEE-PCAUVNBSSA-N',
  'HAMNKHJHOZJTEE-LHFUQYOZSA-N',
  'HAMNKHJHOZJTEE-VZRAIFRISA-N',
  'HAMNKHJHOZJTEE-FLHCDVKPSA-N',
  'RZFRDPQVYPLNIF-XVNBXDOJSA-N',
  'RKYZCZCZRFHTAV-LORJBHLZSA-N',
  'DHZBEENLJMYSHQ-YUMGAWCOSA-N',
  'SJSOFNCYXJUNBT-UHFFFAOYSA-N',
  'YOWUDEPRYODFBZ-SNVBAGLBSA-N',
  'QIDVAQFKQKKYPJ-SNVBAGLBSA-N',
  'CLHRRLZEKMQHFZ-ZOQAJNJPSA-N',
  'CLHRRLZEKMQHFZ-HZHVFOLNSA-N',
  'YMHFOVZNDVWJCE-XNCJUZBTSA-N',
  'VRNZBLTUSHYQEF-IWSQBXEPSA-N',
  'SPKNARKFCOPTSY-JBABRTIHSA-N',
  'SPKNARKFCOPTSY-XWPZMVOTSA-N',
  'OYOAZXRTZINOMW-ACLDMZEESA-N',
  'WFOADYFXGWWIRB-JXVPXHAGSA-N',
  'TVSNWZPMYISSOD-LPEHRKFASA-N',
  'TVSNWZPMYISSOD-UTLUCORTSA-N',
  'WDOJAOWSPDIERF-UHFFFAOYSA-N',
  'KEVUCOVVHJNLQA-YVMONPNESA-N',
  'NUGFZCHRZRZHLK-MRVPVSSYSA-N',
  'MOVHCBLRKLLLQI-SNAWJCMRSA-N',
  'ZIOSZYWKPRFNOY-HWKANZROSA-N',
  'WCVRXNVIQWJWOZ-UHFFFAOYSA-N',
  'WBXHOGVKFYXMBX-QRSKOWNHSA-N',
  'JAIZJDIWZLUPEB-BQBZGAKWSA-N',
  'JAIZJDIWZLUPEB-NKWVEPMBSA-N',
  'JAIZJDIWZLUPEB-RNFRBKRXSA-N',
  'JAIZJDIWZLUPEB-RQJHMYQMSA-N',
  'QDINYLSTNVLZAV-DWAQLAQLSA-N',
  'IIIFVUMJBALUGH-UPVLLSTMSA-N',
  'SDNWXRNEYAERFY-UHFFFAOYSA-N',
  'SYZUSGZXGMNHER-UHFFFAOYSA-N',
  'YYANCILJHBCDBI-UHFFFAOYSA-N',
  'DEBOLEIPZTWPMB-UHFFFAOYSA-N',
  'SUZSODJXSTWHAX-UHFFFAOYSA-N',
  'BFGARRLDQSVOQF-UHFFFAOYSA-N',
  'JWPGJSVJDAJRLW-UHFFFAOYSA-O',
  'OMLSYRSLWGSLPR-ZRDIBKRKSA-N',
  'VNGIRXHFLURPAH-WUXMJOGZSA-N',
  'KBBGEMAIBQZBMX-UHFFFAOYSA-N',
  'UXNJNIHKIFJLTE-UHFFFAOYSA-N',
  'ZHZSGODANHLOGP-JQCXWYLXSA-N',
  'ARFHIAQFJWUCFH-KIFNTFBYSA-N',
  'ARFHIAQFJWUCFH-JMUHATKESA-N',
  'DYPFWRCGECJCBK-UHFFFAOYSA-N',
  'FIHPYWGQGLVWSU-UHFFFAOYSA-O',
  'QHLQYTNMSXEBIQ-UHFFFAOYSA-N',
  'BEPGTHDUUROBHM-UHFFFAOYSA-N',
  'FTFOPGZFHHNAAR-UHFFFAOYSA-N',
  'KQLDDLUWUFBQHP-WVBSTYLSSA-N',
  'BXQVVDJZCDTBBB-UHFFFAOYSA-M',
  'ZHQQRIUYLMXDPP-SSDOTTSWSA-N',
  'MAHYVJAEGUGRHA-HTQZYQBOSA-N',
  'LGYCOYCCCKHXGC-UHFFFAOYSA-N',
  'MTUHWXIFEMXXAZ-UHFFFAOYSA-N',
  'BVGIYKRHRXZGIO-JTQLQIEISA-N',
  'QWWUCLLPHZUUDS-UHFFFAOYSA-N',
  'QWWUCLLPHZUUDS-UHFFFAOYSA-O',
  'MHTLPFVHBVOGMZ-UHFFFAOYSA-O',
  'ZRILVGJRAWMJFE-UHFFFAOYSA-O',
  'DGMPVYSXXIOGJY-UHFFFAOYSA-M',
  'MTHASAHNRVFFOM-VIFPVBQESA-N',
  'PIRNZOVZJAMJNC-UHFFFAOYSA-N',
  'IBRKLUSXDYATLG-LURJTMIESA-O',
  'IBRKLUSXDYATLG-ZCFIWIBFSA-O',
  'IBRKLUSXDYATLG-ZCFIWIBFSA-N',
  'ZGMORAIVFRLFQJ-ZCFIWIBFSA-N',
  'LBVCBOPBXJMRED-SECBINFHSA-N',
  'KGKGBTYHOMHEFN-VIFPVBQESA-N',
  'ARIZYLSCDPQLSY-JTQLQIEISA-N',
  'GOOKIFCKRCPTIL-UHFFFAOYSA-N',
  'IGBWWNWDPNGXOJ-VIFPVBQESA-N',
  'IGBWWNWDPNGXOJ-SECBINFHSA-N',
  'CYPIXIJGBJHXHG-VIFPVBQESA-N',
  'CYPIXIJGBJHXHG-SECBINFHSA-N',
  'SGXNGBKSKOHDJP-QMMMGPOBSA-N',
  'SGXNGBKSKOHDJP-MRVPVSSYSA-N',
  'MDPPSAHGELKXFL-UHFFFAOYSA-O',
  'JYTFPUVNNKLBPD-UHFFFAOYSA-N',
  'WJKTWCQUWWUWJC-RRAGMBSWSA-N',
  'WJKTWCQUWWUWJC-XUOSJQGZSA-N',
  'GYQWAMYDGNUNNL-ZETCQYMHSA-N',
  'GYQWAMYDGNUNNL-SSDOTTSWSA-N',
  'JPQOSMXPPUCWDZ-SSDOTTSWSA-N',
  'AMPLTVKIWKZEGO-JTQLQIEISA-N',
  'AMPLTVKIWKZEGO-SNVBAGLBSA-N',
  'PHOUKBDDOYWEMY-YUMGAWCOSA-N',
  'GBJQPSBGSKNYHV-OJYNLAAISA-N',
  'XZXCYBBAXJQLFQ-IMTBSYHQSA-N',
  'UWAZSQUZHSRNTR-UHFFFAOYSA-N',
  'FAVBBTRSLZBNEY-UHFFFAOYSA-L',
  'OUJZJCJPABVTHT-JTQLQIEISA-N',
  'OUJZJCJPABVTHT-SNVBAGLBSA-N',
  'JZQLISGEFWNUTL-MVHNUAHISA-N',
  'GRGXIBOBMHBUAQ-POYBYMJQSA-N',
  'GRGXIBOBMHBUAQ-SVRRBLITSA-N',
  'ZGSNCXKJBYAIOL-UHFFFAOYSA-O',
  'BMLTXAQSFDCMHA-UHFFFAOYSA-O',
  'SVLXGEARAXXBSX-UHFFFAOYSA-N',
  'BPSLFSXCUJYFIR-UHFFFAOYSA-O',
  'LHMSSSMQTCBLSX-JTQLQIEISA-N',
  'FHQRDEDZJIFJAL-UHFFFAOYSA-N',
  'MZLPWDDUDIIZIR-ZETCQYMHSA-N',
  'KUMNGEFTSKDDEM-HWMYAHKASA-N',
  'KUMNGEFTSKDDEM-BBTUGCGASA-N',
  'KUMNGEFTSKDDEM-MUBNBVIASA-N',
  'FVPHWLFPVMYUFV-NRPADANISA-N',
  'YTOJCYQLVTZXDI-AZECVOHWSA-N',
  'CIGWZTJWFIZJFC-HLTSFMKQSA-N',
  'CIGWZTJWFIZJFC-HRDYMLBCSA-N',
  'WZBGMRRSJBIOSX-AGDSKLNSSA-N',
  'YHZJDEGDXGWSHO-DJLDLDEBSA-N',
  'YHZJDEGDXGWSHO-HRDYMLBCSA-N',
  'YHZJDEGDXGWSHO-VGMNWLOBSA-N',
  'GVMLVDWTBSRCIJ-UHFFFAOYSA-N',
  'CMICLHNTUULKJB-FPLPWBNLSA-N',
  'JMCADYVYWBIIPK-UHFFFAOYSA-N',
  'FSHARTIDZHPHND-UHFFFAOYSA-N',
  'WDWYLKVZYIVBTF-UHFFFAOYSA-N',
  'JUOSGGQXEBBCJB-GORDUTHDSA-N',
  'WZZJAYPARCLIPG-JTQLQIEISA-O',
  'WZZJAYPARCLIPG-SNVBAGLBSA-O',
  'XCACCLNWIIMXHQ-UHFFFAOYSA-O',
  'CONDDCCDTHKSBC-VURMDHGXSA-N',
  'DAMBAJDWLIFTNW-YLWLKBPMSA-N',
  'FUVNRBOZKPCLDV-LURJTMIESA-N',
  'FUVNRBOZKPCLDV-ZCFIWIBFSA-N',
  'AZLHFHPCLQLBFN-LPBLVHEISA-N',
  'NZERRTYPTPRCIR-ARSLAPBQSA-N',
  'GQJQWKGFWJGTEP-UHFFFAOYSA-N',
  'MXWOBMFEFUHOFI-UHFFFAOYSA-N',
  'XIDXCFOHGHYXFN-LURJTMIESA-M',
  'XIDXCFOHGHYXFN-ZCFIWIBFSA-M',
  'YHNIJSNHQNDGGJ-UHFFFAOYSA-M',
  'YXWSPTWNJXZXMA-UHFFFAOYSA-N',
  'WVCHTEGJLJZQEH-VZUCSPMQSA-N',
  'RWFBQHICRCUQJJ-JQWIXIFHSA-N',
  'YVZIWTQAOFUJIO-QMMMGPOBSA-N',
  'XWNGIHCMHHKLNE-UHFFFAOYSA-N',
  'FUFWOFSLTRNGNA-QMMMGPOBSA-O',
  'SCYLCJYOOYFXBU-BWNXKKBKSA-N',
  'JUVNMMQESFKFJV-MVHNUAHISA-N',
  'KYHQZNGJUGFTGR-LURJTMIESA-N',
  'KYHQZNGJUGFTGR-ZCFIWIBFSA-N',
  'OLEPHOCAJGNFAB-URJBTRRKSA-O',
  'ZZTWVKQNXKWIHB-UHFFFAOYSA-N',
  'GXLQKKAOIFXVOL-UHFFFAOYSA-N',
  'VYPONAGZHAJHGT-ZBJFTSOASA-N',
  'MAUFTTLGOUBZNA-UHFFFAOYSA-N',
  'IJJFSGHIHZCQGI-UHFFFAOYSA-N',
  'WCTXPCHGTVGRON-SNVBAGLBSA-N',
  'UPPBLFBZDBKTNR-QMMMGPOBSA-N',
  'OFOTZVNSRRCRCX-VMPITWQZSA-N',
  'RWPMUILWEWHZKN-CIUDSAMLSA-N',
  'RWPMUILWEWHZKN-XHNCKOQMSA-N',
  'RWPMUILWEWHZKN-HRDYMLBCSA-N',
  'RWPMUILWEWHZKN-VGMNWLOBSA-N',
  'CJWLGOWMMDDXLV-ZYUZMQFOSA-N',
  'YGMNGQDLUQECTO-UJNFCWOMSA-N',
  'YGMNGQDLUQECTO-SFGNSQDASA-N',
  'YOOGDQUSAKDEKI-JGVFFNPUSA-N',
  'YOOGDQUSAKDEKI-HTQZYQBOSA-N',
  'MAQKQZMHDCFYTD-CIUDSAMLSA-N',
  'NQWBFQXRASPNLB-CIUDSAMLSA-N',
  'VUVQBYIJRDUVHT-MUWHJKNJSA-N',
  'BDXDSAWGUGHUQP-JGVFFNPUSA-N',
  'BDXDSAWGUGHUQP-SFYZADRCSA-N',
  'LASOZNWHPDFLML-HTQZYQBOSA-N',
  'CGEVOYRUHMDHSE-YUMQZZPRSA-N',
  'ORSRMFUEDMCTJU-QXFUBDJGSA-N',
  'ORSRMFUEDMCTJU-NQMVMOMDSA-N',
  'ORSRMFUEDMCTJU-WEDXCCLWSA-N',
  'JHKNAYGQYUKKDQ-YUMQZZPRSA-N',
  'JHKNAYGQYUKKDQ-HTQZYQBOSA-N',
  'VOJBXZDIFIJUKD-HYNBTVFTSA-N',
  'VOJBXZDIFIJUKD-HOMPQPGZSA-N',
  'VOJBXZDIFIJUKD-VJIGKBMESA-N',
  'BVTAIXWVSMPSFL-SECBINFHSA-N',
  'YIVMCXYIUTUOOZ-SNVBAGLBSA-N',
  'LJEYGIUEZKHQIW-YTPBJJJYSA-N',
  'JQLGFJVAPASLOL-ZZXKWVIFSA-N',
  'WWJYPRXNKYXREE-SGRBOOSSSA-N',
  'YNRNIKRFIIHGPK-WTKPLQERSA-N',
  'QKUSWZPEWDLILF-SECBINFHSA-N',
  'UBZPWMGPLMVDNO-UHFFFAOYSA-N',
  'QKYRDLBTCVVFJE-ZCFIWIBFSA-N',
  'RBACRCCJOHPVRS-UHFFFAOYSA-N',
  'GMJLJXNLVMISOW-UHFFFAOYSA-N',
  'ULRBKGCIGBUVLG-MBGOZMDMSA-N',
  'MFGQIFHXSKAWPR-VIFPVBQESA-N',
  'LBNWZGLSMCTAQB-QUBYGPBYSA-N',
  'LBNWZGLSMCTAQB-LHLIQPBNSA-N',
  'SRBSXGSWXUVKPY-WPRPVWTQSA-N',
  'XQHOYOKXFNTNQZ-RNFRBKRXSA-N',
  'XQHOYOKXFNTNQZ-RQJHMYQMSA-N',
  'OKCFVPQLGPDTCC-UHFFFAOYSA-N',
  'XBJDHJQNQRRFFL-UHFFFAOYSA-N',
  'ZZESVQDUWCDFBM-JTQLQIEISA-N',
  'ZZESVQDUWCDFBM-SNVBAGLBSA-N',
  'IBWYIXZIEIPGJL-ZJUUUORDSA-N',
  'CVNFBGPWRFXIDP-QMMMGPOBSA-N',
  'RDIMUEDTLDIZEW-SECBINFHSA-N',
  'DIAWRORHQSYDTG-LKEDHPFLSA-N',
  'DNUDFISZTSNQPJ-ZWPSSFCZSA-N',
  'SEURXENDYJJSDO-DKWSLFAKSA-N',
  'SVNKCHWDJBIZMI-SECBINFHSA-N',
  'KGBKYZFFQHZKLE-QMMMGPOBSA-N',
  'KGBKYZFFQHZKLE-MRVPVSSYSA-N',
  'VPAQOCIIZZGSDX-OIBJUYFYSA-N',
  'ZWMLESXRXFUSQE-UHFFFAOYSA-N',
  'NINSLWBFGHOXJY-KOERYYGSSA-N',
  'HFDYHSZMLSPEAI-PIAOCPBHSA-N',
  'PMAGWBXRCQWPNQ-ZETCQYMHSA-N',
  'QABWODWVYBVOHR-GFXLDLHQSA-N',
  'QABWODWVYBVOHR-KAZIXTOESA-N',
  'MMOBFZFCWIDGIB-LHLIQPBNSA-N',
  'VXOJVQJURAQQOK-FSDSQADBSA-N',
  'BTIKJPRUQUGBSU-MPXCPUAZSA-M',
  'BTIKJPRUQUGBSU-DAGMQNCNSA-M',
  'JWWNTVZAXCYTJC-FSDSQADBSA-N',
  'AOGHESGONXYZMW-XZMZPDFPSA-N',
  'AOGHESGONXYZMW-SZACMFPPSA-N',
  'AOGHESGONXYZMW-PULFBKJNSA-N',
  'AOGHESGONXYZMW-JVZYCSMKSA-N',
  'WXMARWINOVVAEN-QWABEJFVSA-N',
  'OKNGZIPJMVOSQY-ZFVDQJKFSA-N',
  'OKNGZIPJMVOSQY-NBBQQVJHSA-N',
  'HKOAILQLQLJCFO-MMSORMPISA-N',
  'SJSGYYGIRSKXTM-RBXMUDONSA-N',
  'SJSGYYGIRSKXTM-BZNPZCIMSA-N',
  'PHOSJGRFHWCOJR-UWVGGRQHSA-N',
  'PHOSJGRFHWCOJR-NXEZZACHSA-N',
  'XNJDUGALSDZUTA-CHIQAWFVSA-N',
  'XNJDUGALSDZUTA-VEVYYDQMSA-N',
  'BTLWKUIXHYMYIL-HXFLIBJXSA-N',
  'JCWPVPJYCLLPQL-AQZFUDGLSA-N',
  'JCWPVPJYCLLPQL-CXPMVJJISA-N',
  'JCWPVPJYCLLPQL-SCKAFXQUSA-N',
  'YHUYXKZLGRZKAJ-RQJHMYQMSA-N',
  'IDJUDJGASCSDGP-BIIVOSGPSA-N',
  'OYHHNJLVXIIQGO-LEZDYHIDSA-N',
  'YRYGUSBXGHCZEK-JCIYNLPVSA-N',
  'MVKKKYNXENCTKJ-ZCMHJKFASA-N',
  'MKPZLFSGCUYQEY-WYKLRKJWSA-N',
  'MKPZLFSGCUYQEY-YIYNDRPXSA-N',
  'MKPZLFSGCUYQEY-DYBMOJKOSA-N',
  'MKPZLFSGCUYQEY-CSNGHJMDSA-N',
  'MKPZLFSGCUYQEY-UNPLIRBPSA-N',
  'MKPZLFSGCUYQEY-JKPBTABPSA-N',
  'MKPZLFSGCUYQEY-FCOVNKKWSA-N',
  'MKPZLFSGCUYQEY-ONSVQNCISA-N',
  'MKPZLFSGCUYQEY-ITIVWUPMSA-N',
  'SAZJFRBQDIBJEF-NLCJYVHKSA-N',
  'SAZJFRBQDIBJEF-RENNVBTOSA-N',
  'XDSJZVSFNXQKNQ-QNSHHTMESA-N',
  'KPWKPGFLZGMMFX-VHSXEESVSA-M',
  'MOUZVDVFZGJOOS-HXFLIBJXSA-N',
  'MOUZVDVFZGJOOS-XGEHTFHBSA-N',
  'LKTMJNNNZIVEJI-AEJSXWLSSA-N',
  'UWKMXHXTUOGMMZ-OYNCUSHFSA-N',
  'UWKMXHXTUOGMMZ-QXFUBDJGSA-N',
  'JVACJZGMLHSRGA-ZETCQYMHSA-N',
  'SNNJSMNZDVHVIU-QEPMPPCBSA-N',
  'SNNJSMNZDVHVIU-YKJCMVHCSA-N',
  'GSXXKILAEILYRX-CVNHGOGGSA-N',
  'GSXXKILAEILYRX-CCYQRUOZSA-N',
  'SGJAGMWFELNOAM-WKEGUHRASA-N',
  'ITCOWOVATIICJS-YEPSODPASA-N',
  'KOMQDNILFGUPAF-NRNPDCPVSA-N',
  'KNVSYDKAXGHRJZ-QWABEJFVSA-N',
  'KNVSYDKAXGHRJZ-OKJJWFQTSA-N',
  'AOJDAZKPGYADTA-PEBGCTIMSA-N',
  'FFXUKJKVADHZEA-KFINBIDJSA-N',
  'WUHFOIPFQKEGNR-XRIFCOSDSA-N',
  'NEZQWZBCEHOWJS-ZYUZMQFOSA-N',
  'IXVBKLNTWKFEBN-ZGDSCGAWSA-N',
  'BGGIYCDURCYNQZ-YWIQKCBGSA-N',
  'NDGVBBGSPLJJRM-SNVBAGLBSA-N',
  'FQRAKZWEBJPGTM-NXEZZACHSA-N',
  'UTSGPHXOHJSDBC-UHFFFAOYSA-N',
  'OGQMYOKLFYJRGZ-UHFFFAOYSA-N',
  'XNGKCOFXDHYSGR-UHFFFAOYSA-N',
  'CVIDZLCXVGUFAC-UHFFFAOYSA-N',
  'UAGFAMQTBLSQSU-UHFFFAOYSA-N',
  'FBCHAKMLRMZMEL-MBGOZMDMSA-N',
  'XHCSYCLPVDIJNC-YEBTWRFZSA-N',
  'XIOPKILEHGQSHY-VTHCJYECSA-N',
  'RHABCRQHZGGHKU-HTQZYQBOSA-N',
  'RHABCRQHZGGHKU-SFYZADRCSA-N',
  'UKJVBIAAYSSDNV-WYOYIEJBSA-N',
  'UZDVEPSWHCPIPM-WYOYIEJBSA-N',
  'UZDVEPSWHCPIPM-BAZKGXGOSA-N',
  'UZDVEPSWHCPIPM-FWWPZPIUSA-N',
  'HNULJAOABSCBIT-XHNCKOQMSA-N',
  'HNULJAOABSCBIT-HRDYMLBCSA-N',
  'FDFKMTXRKNETHS-DJLDLDEBSA-N',
  'FLLFLUQBZFBTID-UHFFFAOYSA-N',
  'IFQQQYVVFJFUMU-VIFPVBQESA-O',
  'IFQQQYVVFJFUMU-SECBINFHSA-O',
  'RSNWKPGHDZIJSR-UHFFFAOYSA-O',
  'SMRQLVGKTRFMEA-FMIVXFBMSA-N',
  'XVBIUXCFSSYHDX-UHFFFAOYSA-N',
  'QUEUMZDCKNIDDW-UHFFFAOYSA-N',
  'DMVXDDHPDNVNRN-SGIHWFKDSA-N',
  'PTFBPGSVTKNBDK-MRVPVSSYSA-N',
  'SMOSTIXKLUXRDD-QMMMGPOBSA-N',
  'LSXWHXRWALCZSK-KLZKCWAHSA-N',
  'PEULRBDHIYVKNS-UHFFFAOYSA-O',
  'VBVIUKBNFWREGF-ZETCQYMHSA-N',
  'WTTCXOAAHHJUDA-ZETCQYMHSA-N',
  'WTTCXOAAHHJUDA-SSDOTTSWSA-N',
  'RDDQGYUAZFLPQS-UHFFFAOYSA-O',
  'CGPIOORMJIXSIM-AOGGBPEJSA-N',
  'HSDXVAOHEOSTFZ-UHFFFAOYSA-N',
  'XBXQLPOQBBRAHQ-RPOIFPIJSA-N',
  'QJSYDZJVWFTJEM-VHSXEESVSA-O',
  'QJSYDZJVWFTJEM-ZJUUUORDSA-O',

In [58]:
gs_res = apply_gsea(nap_taskid='', params=params, feat=feat, meta=meta,
                    annotated=df, mol_set=mol_set,
                    method='ratio_of_classes')

In [59]:
gs_res.keys()

dict_keys(['Piaui', 'Ceara', 'Paraiba', 'Pernambuco', 'Bahia', 'Rio Grande do Norte', 'Minas Gerais'])

In [64]:
gs_res['Piaui']['class_name'].res2d.head()

,es,nes,pval,fdr,geneset_size,matched_size,genes,ledge_genes
Term,,,,,,,,
CHEMONTID:0000256,0.699671,1.857417,0.00,0.025316,41625,34,OSRIFQMEUWIQSG-HUYIQXHZSA-N;DCPDPBCUPLKQNQ-LDL...,OSRIFQMEUWIQSG-HUYIQXHZSA-N;DCPDPBCUPLKQNQ-LDL...
CHEMONTID:0003909,0.675753,1.806182,0.05,0.033755,15777,44,ZJEGPKOJFMVILW-JEBPEJKESA-N;LCMJGVARRXLCMN-XKI...,ZJEGPKOJFMVILW-JEBPEJKESA-N
CHEMONTID:0000259,0.721462,1.970629,0.00,0.050633,72847,135,BTOWFTWPBCWWEZ-JBGWXCLJSA-N;XBOPOFMGWPIGHK-FKB...,BTOWFTWPBCWWEZ-JBGWXCLJSA-N;XBOPOFMGWPIGHK-FKB...
CHEMONTID:0000258,0.543509,1.362216,0.05,0.168776,28806,73,DSGJHGLCXMRKCC-AAXFWFPKSA-N;LIIOJBIJVPGVGO-JZZ...,DSGJHGLCXMRKCC-AAXFWFPKSA-N;LIIOJBIJVPGVGO-JZZ...
CHEMONTID:0000334,0.730362,1.447661,0.00,0.177215,17665,206,GHSMFVLHRTWFOO-UHFFFAOYSA-O;MFHMTMFSFNMTFQ-RJB...,GHSMFVLHRTWFOO-UHFFFAOYSA-O;MFHMTMFSFNMTFQ-RJB...

In [65]:
gs_res['Piaui']['class_name'].res2d.pval

Term
CHEMONTID:0000256    0.000000
CHEMONTID:0003909    0.050000
CHEMONTID:0000259    0.000000
CHEMONTID:0000258    0.050000
CHEMONTID:0000334    0.000000
CHEMONTID:0000145    0.150000
CHEMONTID:0000323    0.100000
CHEMONTID:0002279    0.150000
CHEMONTID:0000238    0.294118
CHEMONTID:0000123    0.500000
CHEMONTID:0000265    0.550000
CHEMONTID:0002506    0.800000
Name: pval, dtype: float64

In [66]:
gs_res['Piaui']['class_name'].res2d.fdr

Term
CHEMONTID:0000256    0.025316
CHEMONTID:0003909    0.033755
CHEMONTID:0000259    0.050633
CHEMONTID:0000258    0.168776
CHEMONTID:0000334    0.177215
CHEMONTID:0000145    0.192405
CHEMONTID:0000323    0.253165
CHEMONTID:0002279    0.278481
CHEMONTID:0000238    0.326301
CHEMONTID:0000123    0.572152
CHEMONTID:0000265    0.584580
CHEMONTID:0002506    0.658228
Name: fdr, dtype: float64