In [1]:
from pyclassrich.gnps import Proteosafe
import matplotlib.pyplot as plt

from pyclassrich.models import class_enrichment, impact_plot, ont_graph, get_ont_graph
from pyclassrich.utils import *
import pandas as pd
import json

%matplotlib

Using matplotlib backend: <object object at 0x719a94257b30>

In [2]:
params = {
    "mzmine": False,
    "mzmine_batch": False,
    "desc": 'description',
    "gnps_taskid": 'c66bf306c305449e856edc355e61ab20',
    "gnps_nap": False,
    "nap_taskid": '',
    "classify": True,
    "normalization": {
        "perform": True,
        "type": 'TIC'
    },
    "enrich": True,
    "comparison": {
        "classes": '3297,3519',
        "field": 'ATTRIBUTE_samplename',
        "test": 'ttest',
        "vthr": 0.5
    },
    "summarize": True,
    "pcoa": True,
    "pcoa_metric": 'canberra',
    "pcoa_norm": True,
    "pcoa_scale": True,
    "email": 'email@gmail.com'
}

In [3]:
params.keys()

dict_keys(['mzmine', 'mzmine_batch', 'desc', 'gnps_taskid', 'gnps_nap', 'nap_taskid', 'classify', 'normalization', 'enrich', 'comparison', 'summarize', 'pcoa', 'pcoa_metric', 'pcoa_norm', 'pcoa_scale', 'email'])

In [4]:
params

{'mzmine': False,
 'mzmine_batch': False,
 'desc': 'description',
 'gnps_taskid': 'c66bf306c305449e856edc355e61ab20',
 'gnps_nap': False,
 'nap_taskid': '',
 'classify': True,
 'normalization': {'perform': True, 'type': 'TIC'},
 'enrich': True,
 'comparison': {'classes': '3297,3519',
  'field': 'ATTRIBUTE_samplename',
  'test': 'ttest',
  'vthr': 0.5},
 'summarize': True,
 'pcoa': True,
 'pcoa_metric': 'canberra',
 'pcoa_norm': True,
 'pcoa_scale': True,
 'email': 'email@gmail.com'}

In [5]:
gnps = Proteosafe(params['gnps_taskid'], 'FBMN-gnps2')
gnps.get_gnps()

feat = gnps.feat
meta = gnps.meta

meta.head()

                     filename ATTRIBUTE_samplename
0  01_3297_POS_1-3_01_11.mzML                 3297
1  02_3297_POS_1-4_01_12.mzML                 3297
2  03_3297_POS_1-5_01_13.mzML                 3297
3  04_3519_POS_1-6_01_14.mzML                 3519
4  05_3519_POS_1-7_01_15.mzML                 3519

In [6]:
tabgnps = pd.merge(gnps.gnps, gnps.dbmatch, 
                   left_on='cluster index', right_on='#Scan#', 
                   how='left')
tabgnps.head()

,cluster index,parent mass,RTMean,ATTRIBUTE_samplename:GNPSGROUP:3297,ATTRIBUTE_samplename:GNPSGROUP:3519,ATTRIBUTE_samplename:GNPSGROUP:3546,ATTRIBUTE_samplename:GNPSGROUP:BRCO,ATTRIBUTE_samplename:GNPSGROUP:QC,component,#Scan#_x,...,molecular_formula,InChIKey,InChIKey-Planar,superclass,class,subclass,npclassifier_superclass,npclassifier_class,npclassifier_pathway,library_usi
0,130,242.910713,1.122737,0.000000,221.647668,508.981983,0.000000,91.396513,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,144,288.939153,1.174439,98.617290,0.000000,0.351677,0.000000,60.839320,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,150,498.877576,1.137107,6.556746,301.797233,128.284170,0.133582,257.703677,17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,164,408.899835,1.133442,142.471967,90.731158,18.596911,0.065512,107.686899,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,166,226.936371,1.150297,0.000000,830.452133,1218.031553,0.068000,188.115638,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
%%time

annotated = classifyChemWalker('../goldman_full_output_file.csv', 'COCONUT', tabgnps)
annotated.head()

Loading database...

RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InRDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key
RDKit ERROR: [15:39:57] Invalid InChI prefix in generating InChI Key

KeyboardInterrupt:

id InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key
[15:39:57] Invalid InChI prefix in generating InChI Key

In [ ]:
annotated = classifyChemWalker('../goldman_full_output_file.csv', 'COCONUT', tabgnps)
annotated.head()

Loading database...

In [10]:
annotated.shape

(1558, 18)

In [9]:
from pyclassrich.stats import *

In [11]:
tabgnps = tabgnps.rename(columns={'cluster index': 'cluster.index', 'parent mass':'parent.mass', 'SpectrumID':'LibraryID'})

tabgnps.head()

,cluster.index,number.of.spectra,parent.mass,precursor.charge,precursor.mass,sum.precursor.intensity.,G1,G2,G3,G4,...,RTStdErr,UniqueFileSourcesCount,LibraryID,ProteoSAFeClusterLink,AllGroups,DefaultGroups,EvenOdd,SpectrumID,Smiles,INCHI
0,2,26,454.2925,1,454.2925,1.291700e+08,0,0,0,0,...,0,26,Massbank:RP026103 1-palmitoyl-2-hydroxy-sn-gly...,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,CCMSLIB00005738697,[H][C@@](O)(COC(=O)CCCCCCCCCCCCCCC)COP(O)(=O)OCCN,1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-12-13-1...
1,3,26,480.3083,1,480.3083,1.534335e+08,0,0,0,0,...,0,26,Spectral Match to 1-(9Z-Octadecenoyl)-sn-glyce...,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,CCMSLIB00003137012,NaN,NaN
2,4,26,494.3239,1,494.3239,7.287906e+07,0,0,0,0,...,0,26,NaN,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,NaN,NaN,NaN
3,5,26,466.2926,1,466.2926,5.508946e+07,0,0,0,0,...,0,26,NaN,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,NaN,NaN,NaN
4,6,26,452.2768,1,452.2768,6.042495e+07,0,0,0,0,...,0,26,NaN,https://gnps.ucsd.edu/ProteoSAFe/result.jsp?ta...,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df = univariate(annotated, tabgnps, 
                params, feat, meta)

df.head()

,cluster.index,parent.mass,RTMean,LibraryID,Identifier,InchiKey,kingdom_name,superclass_name,superclass_id,class_name,...,subclass_name,subclass_id,Smiles,InChI,row ID,row m/z,row retention time,fchange,pval,cpval
597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,338.341339,17.766594,1.783147,0.190487,0.333560
0,2.0,454.2925,11.6428,Massbank:RP026103 1-palmitoyl-2-hydroxy-sn-gly...,SN00048579,YVYMBNSKXOXSKW-HXUWFJFHSA-N,Organic compounds,Benzenoids,CHEMONTID:0002448,Phenol ethers,...,Anisoles,CHEMONTID:0000138,[H][C@@](O)(COC(=O)CCCCCCCCCCCCCCC)COP(O)(=O)OCCN,InChI=1S/C21H44NO7P/c1-2-3-4-5-6-7-8-9-10-11-1...,2,454.292475,11.642782,3.524664,0.003093,0.022670
1,3.0,480.3083,11.9519,Spectral Match to 1-(9Z-Octadecenoyl)-sn-glyce...,SN00099478,MURVJQSDIIPTEC-GTTGMRKWSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Prenol lipids,...,Sesquiterpenoids,CHEMONTID:0001550,,InChI=1S/C30H41NO4/c1-20(12-13-24-21(2)10-8-15...,3,480.308327,11.951862,2.156446,0.009297,0.039368
2,4.0,494.3239,12.6089,NaN,SN00312735,DQZJPKYNSKJWBF-NONLCYDASA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Prenol lipids,...,Diterpenoids,CHEMONTID:0001551,,InChI=1S/C31H43NO4/c1-24(13-9-15-26(3)23-29(33...,4,494.323893,12.608921,86.271250,0.000485,0.007785
3,5.0,466.2926,11.4456,NaN,SN00028323,RDBVGLHGYXTTIF-GEVWXPSMSA-N,Organic compounds,Lipids and lipid-like molecules,CHEMONTID:0000012,Prenol lipids,...,Sesquiterpenoids,CHEMONTID:0001550,,InChI=1S/C25H37F2N3O3/c1-5-28-24(33)30-20-7-9-...,5,466.292625,11.445601,146.257554,0.001940,0.017259

In [13]:
df.columns

Index(['cluster.index', 'parent.mass', 'RTMean', 'LibraryID', 'Identifier',
       'InchiKey', 'kingdom_name', 'superclass_name', 'superclass_id',
       'class_name', 'class_id', 'subclass_name', 'subclass_id', 'Smiles',
       'InChI', 'row ID', 'row m/z', 'row retention time', 'fchange', 'pval',
       'cpval'],
      dtype='object')

In [14]:
chemrich = df.copy().loc[~df['cluster.index'].isnull(),
                         ['Identifier', 'class_name', 'InChI', 
                          'pval', 'fchange']]

chemrich.columns = ['Compound_Name', 'Class', 'InChI', 'pvalue', 'foldchange']

clusterdf = class_enrichment(chemrich, cfield='Class', nfield='Compound_Name')
clusterdf.head()

,name,pvalues,adjustedpvalue,keycpdname,alteredMetabolites,upcount,downcount,upratio,altratio,csize,xlogp
0,Phenol ethers,0.00479489,0.00733336,SN00048579,3,2,1,0.666667,0.750000,4,6.05766
1,Prenol lipids,1.35954e-33,3.5348e-32,SN00163714,50,31,19,0.620000,0.641026,78,4.60680
2,Naphthothiazoles,1.15473e-07,7.50577e-07,SN00007859,3,2,1,0.666667,1.000000,3,1.58140
3,Benzene and substituted derivatives,8.52085e-05,0.000301625,SN00085381,5,2,3,0.400000,0.312500,16,2.89970
4,Carboxylic acids and derivatives,0.000520264,0.00122971,SN00105917,10,7,3,0.700000,0.303030,33,3.48240